### ISSUE TITLE
No title tags generated

### ISSUE THREAD

**Issue by accaldwell** [woothemes/storefront#100]
As of version 1.2.2, title tags are no longer being generated on my site. This appears to have to do with commit 515882c42befc616e99af62e12699d55ebf17846 which pulled out all of the code that was generating titles.

Im using wordpress 4.0.1 -- not sure if the theme is now reliant on 4.1. I dont know if the code removal was a mistake, but I dont see how the theme can render titles, at least with wordpress <4.1, without the code that was removed.

**Comment by accaldwell** [comment]
I can confirm that restoring the code removed in 515882c42befc616e99af62e12699d55ebf17846 to the latest git version fixes my issue.

**Comment by jameskoster** [comment]
Hey @accaldwell WordPress 4.1 is a requirement. 

If you have a reason not to update then you can hook a custom title function of your own into `wp_head`.
