### ISSUE TITLE
WooCommerce Support nag

### ISSUE THREAD

**Issue by slash1andy** [woothemes/storefront#108]
http://cld.wthms.co/10lVf

Got this when I activated 2.3 with Storefront 1.2.5

**Comment by jameskoster** [comment]
@slash1andy Hmm you shouldn't: https://github.com/woothemes/storefront/blob/master/inc/functions/setup.php#L84

I've been working with 2.3 since development begun and not seen this. Any further info on your setup that might have influenced this?

**Comment by slash1andy** [comment]
@jameskoster I was previously on 2.3, then downgraded to check on something. When I was on it before, there was no nag. After switching to 2.2.10, I updated Storefront. I then switched back to 2.3, and upon that, I get the nag. 

Also weird from the System Status Report: http://cld.wthms.co/eBDA 

WC Version                2.3.0
WC Database Version       2.3.0
Log Directory Writable    ✔ /srv/www/woocommerce/htdocs/wp-content/uploads/wc-logs/
WP Version                4.1
WP Multisite              –
WP Memory Limit           128 MB
WP Debug Mode             –
Language                  en_US

Server Info               nginx/1.6.1
PHP Version               5.5.9-1ubuntu4.4
PHP Post Max Size         50 MB
PHP Time Limit            30
PHP Max Input Vars        1000
SUHOSIN Installed         –
MySQL Version             5.5.38
Max Upload Size           50 MB
Default Timezone is UTC   ✔
fsockopen/cURL:           ✔
SoapClient:               ✔
Remote Post:              ✔
Remote Get:               ✔

I am running all this on a VVV setup.

**Comment by jameskoster** [comment]
Hmm I tried switching between WooCommerce versions and don't see the nag. Weird. It's not a network installation or something?

That system status thing is an issue in WooCommerce core. We shouldn't recommend people use a child theme like that without more of an explanation.

**Comment by slash1andy** [comment]
It's not network installed or anything funky, really. I keep it lean and "normal" because I test customer issues on it.

**Comment by jameskoster** [comment]
I'll leave this open, see if anyone else reports it. Hard to debug when I can't replicate though xD

**Comment by slash1andy** [comment]
https://github.com/woothemes/woocommerce/issues/7196

I think this is related, so it's more of a WooCommerce bug than Storefront.
