### ISSUE TITLE
Sidebar appeaing above page content

### ISSUE THREAD

**Issue by jamiemarsland** [woothemes/storefront#111]
Using version 1.2.5. The sidebar is appearing full width above the page content.  See screenshot.

![storefont issue](https://cloud.githubusercontent.com/assets/3070779/5886347/ca0dd668-a391-11e4-82e7-2bd20d65071f.png)

**Comment by jameskoster** [comment]
That's very strange. It's not actually the sidebar, that's the header widget region. I've tweaked the order those widget regions appear in the dashboard (Appearance > Widgets). Not sure why that actually moves the widgets though. 

However you should just be able to manually move them back. I'll keep my eye on this.
