### ISSUE TITLE
logo using jetpack

### ISSUE THREAD

**Issue by kelderkold** [woothemes/storefront#113]
![flyandtielogopc](https://cloud.githubusercontent.com/assets/10684010/5887855/323c765e-a3e7-11e4-8635-1a8b5e50442e.png)
![flyandtielogophone](https://cloud.githubusercontent.com/assets/10684010/5887856/38633202-a3e7-11e4-8b0f-b6dbb480343c.png)

When installing Jetpack and using a logo thru this, the logo looks fine on pc version, but looking at my tablet phone, the logo is all over and repited several times in the menu :(

**Comment by jameskoster** [comment]
That doesn't look like the logo. I think it's the header background image setting you've used ;-)

Please post queries like this on the wordpress.org forums. Github is for bug reports.

Thanks.
