### ISSUE TITLE
Product Image in cart doesn't show in 1.2.5

### ISSUE THREAD

**Issue by tarvalian** [woothemes/storefront#114]
This is coming from woocommerce.css: 

```
table.cart .product-quantity .minus, table.cart .product-quantity .plus, table.cart .product-thumbnail {
display: none;
}
```

Is there a reason the product thumbnail in the cart is set to display none?  Was this supposed to be to turn it off in mobile and the styles to display it in larger browsers just got missed, perhaps?

**Comment by jameskoster** [comment]
Yeah it's to save space. Setting the cart page to use the Full Width template reveals all :-)
