### ISSUE TITLE
Add RTL Support

### ISSUE THREAD

**Issue by mattyza** [woothemes/storefront#122]
Add support for languages which run right to left.

This can be done via an `rtl.css` file, which is loaded automatically when WordPress runs an RTL language.

Tools to use for creation and testing of this RTL file are the RTLer and RTL Tester WordPress plugins.

**Comment by jameskoster** [comment]
This is a pretty big task. I've looked to see if there's a way we can do it with grunt but not had much success. There are ways to 'flip' the css, but unfortunately I can't find one that ignores styles that are irrelevant like color etc. They all seem to assume you'd be serving ltr _or_ rtl, not just serving  ltr then overwriting the appropriate styles which is the way WP does it. Shame.

**Comment by mattyza** [comment]
Yeah, it requires overloading of stylesheets.

Something to explore in future.

On Wednesday, February 4, 2015, James Koster <notifications@github.com>
wrote:

> This is a pretty big task. I've looked to see if there's a way we can do
> it with grunt but not had much success. There are ways to 'flip' the css,
> but unfortunately I can't find one that ignores styles that are irrelevant
> like color etc. They all seem to assume you'd be serving ltr *or* rtl,
> not just serving ltr then overwriting the appropriate styles which is the
> way WP does it. Shame.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/woothemes/storefront/issues/122#issuecomment-72851756>
> .
>


-- 
Matt Cohen
Chief Product Officer, WooThemes

http://woothemes.com/
http://matty.co.za/

Ask me questions via Clarity: https://clarity.fm/mattcohen/

**Comment by jameskoster** [comment]
rtl stuff here https://github.com/woothemes/storefront/commit/9df04bb962250884d27119f9b403cd0bc0a873e8
