### ISSUE TITLE
Storefront 1.3.0 Static Page Appearance

### ISSUE THREAD

**Issue by Viktoria-Michaelis** [woothemes/storefront#130]
Today I updated to Storefront 1.3.0.

The first thing that I noticed is that the 'white space' between the header section and the first post or first menu item on the front page has vanished. The headline or category title is now directly under the header image.

For the menu I have been able to correct this messy appearance by inserting a blank text widget. This does not work, obviously, for the main area of the page.

Clicking through to further pages on the blog section, the Breadcrumbs widget appears and provides a decent space between header image and text: the page looks neat and tidy again, well proportioned. The same goes for all other pages where the Breadcrumb appears.

I would like to have this clear and simple layout feature - a suitable space between header and headline - back again without having to go into the code and change it. A cramped and badly laid out front page is not what I want.

https://smallpress-books.com - cramped front page
https://smallpress-books.com/page/2/ - good layout page.

**Comment by jameskoster** [comment]
Ah, this is because you're using a blog page as the homepage. I'll add a fix for this in the next release.

**Comment by Viktoria-Michaelis** [comment]
Excellent, thank you very much.
