### ISSUE TITLE
Add a 'mobile' menu location

### ISSUE THREAD

**Issue by jameskoster** [woothemes/storefront#132]
Currently we have two menu locations:

* Primary - The main navigation
* Secondary - The smaller navigation adjacent to the search bar

The secondary menu is simply hidden for screens smaller than 768px and the full primary menu is displayed. The drawbacks are obvious; potentially important content in the secondary navigation isn't available and vice versa, superfluous (to handheld users) content in the primary nav is displayed regardless.

A dedicated 'handheld' or 'mobile' location will allow folks to create a menu specific to mobile with complete control of its contents.

**Comment by jobthomas** [comment]
A customer was not happy his top menu got lost on mobile.

**Comment by hlashbrooke** [comment]
I think it's a great idea - will offer a lot more flexibility and just makes more sense :)
