### ISSUE TITLE
Display child theme name in the footer credit, if using a child theme

### ISSUE THREAD

**Issue by mattyza** [woothemes/storefront#134]
From our child theme demo: http://cl.ly/image/36340G3w1X1r

Perhaps it's worth dynamically swapping this to the child theme, or displaying the child theme name along with Storefront, if it's present.

Thoughts @jameskoster ?

**Comment by jameskoster** [comment]
Dunno. I like 'Storefront' because it's a generic word that people who don't even know WordPress will understand.

I mean we could say 'Built using Storefront and the Boutique child theme' but that seems a bit much to me...

@warrendholmes any input? :p
