### ISSUE TITLE
Quantity buttons

### ISSUE THREAD

**Issue by mathew07** [woothemes/storefront#139]
How can I remove those additional quantity buttons inside this box on product page? Picture: 
![1](https://cloud.githubusercontent.com/assets/10978798/6381469/bf2619b2-bd41-11e4-88ef-4c361f61261b.png)

**Comment by jameskoster** [comment]
You might want to leave those there, the latest version of WooCommerce removes the outer +/- buttons.

Please post support queries on the wordpress.org forum.
