### ISSUE TITLE
Adjust iframe size in products

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/storefront#143]
If you add a YouTube video to the product description, the iframe is half hidden because it's bigger than the description div.

Using vertical tabs.

**Comment by jameskoster** [comment]
I reckon we should just recommend folks install https://wordpress.org/plugins/fitvids-for-wordpress/

Agreed?

**Comment by SiR-DanieL** [comment]
It's a bit old. Does it work properly yet?

Anyway yes i agree. Not everybody uses videos, it's not worth to include the script in Storefront.

**Comment by jameskoster** [comment]
Hmm, yeah the plugin is probably bundling an outdated version of fitvids. That's not our problem though and I agree it's not worth including the script in Storefront. I guess we'll tackle this as it arises.
