### ISSUE TITLE
Tags for version 1.3.1?

### ISSUE THREAD

**Issue by tidalvirus** [woothemes/storefront#148]
Hi,

I'm not sure if this counts as a valid issue, but I'm trying to check out your latest version via git, and notice that there isn't a tag/release to correspond to your current download of '1.3.1'.

Perhaps I am missing something, or the tag was forgotten on the last change?

Thanks!

Sid

**Comment by jameskoster** [comment]
Looks like I forgot to tag 1.3.1, sorry about that.

1.4.0 is latest though (currently being reviewed), so I suggest checking that out.
