### ISSUE TITLE
storefront_cart_link() returns price excluding tax

### ISSUE THREAD

**Issue by edbloom** [woothemes/storefront#149]
Test case: 
1.) Taxes enabled
2.) Prices entered exclusive of tax
3.) Display Prices in the Shop - Including tax
4.) Display Prices During Cart and Checkout - Including tax
5.) Single Standard tax rate setup and working correctly everywhere - except when called via header.php via storefront_header

Value retuned and displayed in the mini cart is the cart total excluding VAT. 
Example here
http://i.imgur.com/xflS4A4.png

Latest prod releases of WP, WC and Storefront - no other plugins active - full system report here
http://pastebin.com/NWh8Vb7h

Any ideas?

**Comment by jameskoster** [comment]
Any input here @SiR-DanieL ? You made this tweak from total to subtotal. It probably should display inclusive of tax in this example. What do you think?

**Comment by SiR-DanieL** [comment]
I don't think this is an issue with my PR.

I changed from `get_cart_total` to `get_cart_subtotal` which also includes taxes into the [amout if needed](https://github.com/woothemes/woocommerce/blob/557a304326f309538ad1f5b2cfa620fb8bd0c6ed/includes/class-wc-cart.php#L2004).

**Comment by jameskoster** [comment]
So the cart link here http://i.imgur.com/xflS4A4.png should display inclusive of tax?

**Comment by SiR-DanieL** [comment]
I think so

**Comment by jameskoster** [comment]
@edbloom please check the core WooCommerce cart widget. That uses `get_cart_subtotal` as well.

**Comment by edbloom** [comment]
Hi @jameskoster 
Sorry for the delayed response.
The core WooCommerce cart widget is fine. (i.e. displays values including vat). I dropped this into a standard sidebar to confirm via Appearance -> Widgets.

But doesn't solve the original issue I reported. When using Storefront - the cart value within the theme displays the total ex. VAT - am I missing something?

This is distinct from the core cart widget. Looking at the code in Storefront it looks like it's calling WC_Widget_Cart - is this the same core cart widget?

If so, it doesn't make sense that one call to it in the header would display totals ex. VAT - and another call in the sidebar would show different totals?

**Comment by edbloom** [comment]
ah - is it this function that is the issue? Looks to be calling `get_cart_total()`

    if ( ! function_exists( 'storefront_cart_link' ) ) {
	function storefront_cart_link() {
		if ( is_cart() ) {
			$class = 'current-menu-item';
		} else {
			$class = '';
		}
		?>
		<li class="<?php echo esc_attr( $class ); ?>">
			<a class="cart-contents" href="<?php echo esc_url( WC()->cart->get_cart_url() ); ?>" title="<?php _e( 'View your shopping cart', 'storefront' ); ?>">
				<?php echo wp_kses_data( WC()->cart->get_cart_total() ); ?> <span class="count"><?php echo wp_kses_data( sprintf( _n( '%d item', '%d items', WC()->cart->get_cart_contents_count(), 'storefront' ), WC()->cart->get_cart_contents_count() ) );?></span>
			</a>
		</li>
		<?php
	}
}

**Comment by jameskoster** [comment]
@edbloom I think you're not using the latest Storefront? `storefront_cart_link()` should call `get_cart_subtotal()`. What you pasted is calling `get_cart_total()` which would explain the issue.

Try performing an update?

**Comment by edbloom** [comment]
@jameskoster  - argh! i was SURE I checked that before posting this - i was out of date. sorry about that - issue closed.

**Comment by jameskoster** [comment]
not a problem!
