### ISSUE TITLE
Extra space on right side of screen when Post Archives page is set in Reading settings

### ISSUE THREAD

**Issue by jamiemarsland** [woothemes/storefront#152]
The blog archives page (that you set as the posts page in Reading settings) has extra space on the right of the page. See screenshot below. Using Storefront version 1.4.2. 

![storefront issue](https://cloud.githubusercontent.com/assets/3070779/6919511/8bff8aa4-d7af-11e4-88ec-12c92762850b.png)

Also here's a link to a short video that shows it. 

https://vimeo.com/123729607

**Comment by jameskoster** [comment]
Not seeing this issue. Any potential plugin conflicts?

**Comment by jameskoster** [comment]
Closing this, please reopen with more info if applicable :-)
