### ISSUE TITLE
most right review start not fully showing on shop page with right widget bar

### ISSUE THREAD

**Issue by jobthomas** [woothemes/storefront#155]
as the title says: basic storefront install 

![http://cld.wthms.co/AstE](http://cld.wthms.co/AstE+)

**Comment by jameskoster** [comment]
Which browser is this? And is it latest Storefront?

**Comment by jobthomas** [comment]
Safari

WC 2.3.7
Storefront 1.4.2

http://shop.jobthomas.com/

**Comment by jobthomas** [comment]
(also happening without sidebar btw)
