### ISSUE TITLE
Lower-level dropdown menus display issue

### ISSUE THREAD

**Issue by danieldudzic** [woothemes/storefront#157]
When you hover over a parent element, it causes all lower parents to display their child items: http://cld.wthms.co/17VxO

_Link to the ticket: https://woothemes.zendesk.com/agent/tickets/278937_

**Comment by jameskoster** [comment]
Unable to replicate, not seen it reported elsewhere either. Seems like the sort of thing people would be mass-reporting. 

Probably something up with their install.

FYI you do not update Storefront via the Updater.

**Comment by danieldudzic** [comment]
@jameskoster 

Please re-open, I was able to replicate this on my local installation.

Just tested this with version 1.4.4, and still the same issue occurs.

**Comment by jameskoster** [comment]
Didn't realise you meant the third level dropdown, I didn't even have that set up on my local, sorry! Should work fine, 3rd level and beyond.
