### ISSUE TITLE
Secondary Menu changes and adding a customer name - in StoreFront theme

### ISSUE THREAD

**Issue by healiny** [woothemes/storefront#158]
I'm interested that top menu (Secondary Menu) will change depending on the customer login.
If the customer is offline - display LogIn and Sign Up, And will link the appropriate pages.
if connected - display customer name, edit account and more.. (LogOff works right now).

Would love to know how to do it or documentation where I can create it.
Best regards

![log-in-customer](https://cloud.githubusercontent.com/assets/11602443/7074295/0c3054ca-df02-11e4-81ea-fed50ff89be2.jpg)

**Comment by jameskoster** [comment]
Please only post bug reports on github. Thanks :-)
