### ISSUE TITLE
Pluggable Functions

### ISSUE THREAD

**Issue by healiny** [woothemes/storefront#161]
In directoeies - /storefront/inc/.. the mostly functions is pluggable.
In file - /storefront/inc/woocommerce/functions.php,
There are some useful functions without pluggable.

Like - storefront_loop_columns, storefront_related_products_args, storefront_products_per_page.

First - I like to know if it intentionally or bug?
Secend - Is there a way to change the function  storefront_loop_columns in my child-theme,
Or ather way without overwrite the data in an update Storefront?

**Comment by jameskoster** [comment]
None of those functions need to be pluggable are the values they return are filterable.

**Comment by healiny** [comment]
Okay, and how do I use these values through the filter?
