### ISSUE TITLE
Code issue?

### ISSUE THREAD

**Issue by sdbish** [woothemes/storefront#162]
configuring Storefront-sorting in customize, removing product sorting has no effect.

![screen shot 2015-04-14 at 10 42 33 am](https://cloud.githubusercontent.com/assets/11945067/7139351/c30ffbe8-e293-11e4-8284-841cf29ba44a.png)

Also the settings are not being displayed properly on web.

![screen shot 2015-04-14 at 10 43 01 am](https://cloud.githubusercontent.com/assets/11945067/7139359/cbabe154-e293-11e4-8329-40bc2b9c90b0.png)

I think it might be the product sorting drop down.

Check out the "remove this item from cart button" as well, since the previous accessibility update when you click the button (red x next to product in cart view) there is an accessibility box that is displayed from the "x button" all the way to the edge of the browser

**Comment by sdbish** [comment]
I just noticed that the product sorting, product result count and number of pages is appearing both above and below the "shop".  There is no control of the bottom and minimal of the top. 1.4.2 had control and I think only sorting at top with the rest below.  But maybe that was my setting?  either way, it should be corrected to be operational.  Personally I preferred the way 1.4.2 displayed.

**Comment by sdbish** [comment]
If it is my issue, and not the theme, please let me know how to fix.  website is www.airgunproshop.com

**Comment by jameskoster** [comment]
Hi,

This is a conflict with the latest version of Storefront. A new version of the customiser extension will be available to download soon.

**Comment by sdbish** [comment]
Gotcha.  Thanks for the heads up.

**Comment by sdbish** [comment]
did you happen to check out that "remove product from cart" button/accessibility issue?

**Comment by jameskoster** [comment]
I'm not seeing that, could you share a screenshot?

**Comment by sdbish** [comment]
yes I can
![screen shot 2015-04-14 at 1 23 18 pm](https://cloud.githubusercontent.com/assets/11945067/7142889/b28c69e4-e2a9-11e4-9b12-878c7db20fea.png)

it seems to happen where ever you click the remove button, from the dropdown cart on sticky header, from the cart displayed in sidebar, or from the main cart page.  go to www.airgunproshop.com add something to cart, view cart, then click the button to remove it.  it should appear.  Although I am viewing via firefox, maybe that is an issue?

**Comment by jameskoster** [comment]
I see. It's a firefox issue, doesn't seem to happen in other browsers. The cause is the text indent applied to that button. Because this is a firefox issue, I probably won't address this in core and would recommend that you fix this via your child theme.
