### ISSUE TITLE
Product Page Navigation on Categories

### ISSUE THREAD

**Issue by moorsie** [woothemes/storefront#166]
Since updating to 1.4.3, my default shop page, which displays only categories now has a page navigation that navigates across every product within every category

![screen shot 2015-04-17 at 13 09 23](https://cloud.githubusercontent.com/assets/11993680/7201780/1153f8f6-e503-11e4-986f-3e8d44287113.png)

**Comment by jameskoster** [comment]
As mentioned in the release notes we re-organised the sorting/pagination in 1.4.3: https://github.com/woothemes/storefront/releases/tag/version%2F1.4.3

This is just the WooCommerce pagination function and it should be present beneath your products/categories as well. If you don't like it you can remove / hide it via child theme.
