### ISSUE TITLE
Dropdown menu on the iPad (re-)loads the page on select

### ISSUE THREAD

**Issue by danieldudzic** [woothemes/storefront#167]
_Screenshot: http://cld.wthms.co/137Za_ ( can't really show the issue )_

_Link to the ticket: https://woothemes.zendesk.com/agent/tickets/281402_

**Comment by stompweb** [comment]
I don't think it reloads the page but it loads in item you click on. So basically the dropdown menu is not working - is that right?

**Comment by jameskoster** [comment]
Hmm this seems to have happened after the accessibility update which changed how the dropdowns worked slightly. I'll spend some time investigating this this week.
