### ISSUE TITLE
How to create a page that display all posts

### ISSUE THREAD

**Issue by tonychenc** [woothemes/storefront#170]
Hi Folks, How to create a page that display all posts?
I only see full width and home page templates, but they're for displaying page content. 
I noticed single.php is quite close to what I'm looking for, but it doesn't start with template.

**Comment by jameskoster** [comment]
Hi,

Github is for reporting bugs, please post support requests on the wordpress.org forums.

To quickly answer this, assuming you're using a static homepage, just create a new page titled 'blog' or whatever, then set that as your posts page in Settings > Reading.

**Comment by tonychenc** [comment]
Sorry. I'm a newbie to wordpress. Got it. Thank you!
