### ISSUE TITLE
Outline color on click is still present in v1.4.4

### ISSUE THREAD

**Issue by stuartduff** [woothemes/storefront#171]
I have had a few customers report that v1.4.4 didn't resolve the outline that is around products when clicking on the product or the product title. it also happens when clicking on any URL on the site with storefront installed

This is also still happening on both of my support installations too.

Screenshot: http://cld.wthms.co/1c9o5

Screenshot: http://cld.wthms.co/1hGBE

Screenshot:  http://cld.wthms.co/CwFE

**Comment by wizardmadness** [comment]
facing same problem after update :(

**Comment by wizardmadness** [comment]
add this 

a:focus {outline:none; }

**Comment by jameskoster** [comment]
It's supposed to be there. It's an accessibility enhancement.

http://www.woothemes.com/2015/03/storefront-1-4-2-now-more-accessible/
