### ISSUE TITLE
Have a bug in Storefront Parallax Hero plugin

### ISSUE THREAD

**Issue by healiny** [woothemes/storefront#174]
Since the last update to version 1.2.0 plugin 
Created a visual bug particularly noticeable on mobile phones.

Background picture cut at the top, when I scroll the page. 
The bug also appears in storefront demo, so I sent a picture with the demo photo in chrome.

![storefront parallax hero](https://cloud.githubusercontent.com/assets/11602443/7453622/d016faae-f273-11e4-8dee-d9f56a89952c.jpg)

**Comment by jameskoster** [comment]
Hey,

Could you try a hard refresh? I'm not seeing that on the demo?

**Comment by healiny** [comment]
Hi,

Certainly I did a hard refresh. It happens in all 3 browsers on PC. (ie, ff, Chrome)

It seems the worst in a mobile phone, on Android system.
I have LG-G3, and old Sony Ericson Experia.
So sure you will recognize the bug.

Thanks.

**Comment by jameskoster** [comment]
Hey,

I'm away atm but will look into this when I get back. I can't replicate right now but will spend some time with it asap.

**Comment by healiny** [comment]
O.K. Thanks

**Comment by healiny** [comment]
Hi jameskoster
I'm still waiting for you come back from the ATM.
What's going on?
