### ISSUE TITLE
Add functionality to reorder the output of homepage featured products

### ISSUE THREAD

**Issue by stuartduff** [woothemes/storefront#177]
Adding the ability to reorder the homepage featured products via the filter and the order and orderby parameters would be cool. This would allow as an example the ability to easily randomize the featured products and the parameters are ones that area available in the WC shortcode.

**Comment by jameskoster** [comment]
Nice one dude, thanks.

This can go in 1.4.5 though, it's not live yet xD Please update the style.css version no's and changelog and I'll merge.

Thanks again!
