### ISSUE TITLE
storefront_social_icons not called

### ISSUE THREAD

**Issue by mountainash** [woothemes/storefront#182]
There is a function for "Display social icons" in template-tags.php but it's never called.

Why is "storefront_social_icons" included?

**Comment by jameskoster** [comment]
Hey, this is a function that integrates with our 'Subscribe and Connect' plugin. We removed the hook though, as the future of the plugin is uncertain.

If you'd like to create a social icon menu, you might be interested in this document: http://docs.woothemes.com/document/create-a-social-icon-menu/

Cheers
