### ISSUE TITLE
selects shouldn't have a font-family declaration

### ISSUE THREAD

**Issue by jameskoster** [woothemes/storefront#185]
`select {
font-family: initial !important;
}`

to account for child themes.

**Comment by Ohar** [comment]
@jameskoster 
This enhancement force me to get all `select`s as `font-family: serif`, which is `Times New Roman` usually. 
If I don`t want it, I need to start selector war with `!important` and so on.
I don`t count this as useful enhancement, do you?

**Comment by jameskoster** [comment]
@Ohar it shouldn't. It should set all `selects` font family to the browser default. Generally you shouldn't change that either, hence the `!important` declaration.

**Comment by Ohar** [comment]
browser default = `serif` → `Times New Roman`
Surely I _should_ change it, bcz serif font is bad idea for entorely web and for my site design too.

**Comment by jameskoster** [comment]
Which browser sets the font on selects to `serif` by default?
