### ISSUE TITLE
RTL: only include diffs from the theme style.css

### ISSUE THREAD

**Issue by yoavf** [woothemes/storefront#194]
`rtl.css` currently includes references to ```.woocommerce-tabs``` which don't seem to come from `style.css`. Specifically here, this causes some issues with the tabs arrow on mobile:

![](https://cldup.com/jAX8Id8YCQ.png)
(it's pointing left instead of down)

This should probably be left out and updated on woocommerce itself.

**Comment by jameskoster** [comment]
Ah, this is because the mobile/desktop tab layout is different (tabs are adjacent to panels on desktop). The arrow is overwritten for rtl, will just need to specify the icon for handheld in rtl.css as well.
