### ISSUE TITLE
Automatic resize of oEmbeds

### ISSUE THREAD

**Issue by mjepson** [woothemes/storefront#196]
When adding a oEmbed (like a Vimeo), it doesn't automatically set the correct width. 

I have worked around this by setting

`
if (!isset ($content_width)) {
	$content_width = 670;
}
`

in my functions.php file, but the problem with this is that it doesn't auto scale for responsive.

**Comment by jameskoster** [comment]
The content width is already defined here: https://github.com/woothemes/storefront/blob/master/inc/functions/setup.php#L12

It's set to 980 to account for pages using the full width template.

For videos, it's recommended to install a plugin to handle that, such as fitvids. https://wordpress.org/plugins/fitvids-for-wordpress/
