### ISSUE TITLE
Storefront Homepage template not compatible with Jetpack Mobile Theme

### ISSUE THREAD

**Issue by mikeyarce** [woothemes/storefront#201]
Jetpack's Mobile Theme looks at your site's Reading Settings to output the content of your site.  When using Storefront, and you have the Homepage template selected for your Front Page and use Jetpack's Mobile Theme, you get something like this:
<img width="652" alt="screen shot 2015-07-16 at 1 41 18 pm" src="https://cloud.githubusercontent.com/assets/3220162/8734665/543cd378-2bc0-11e5-9143-2be90d61ff18.png">
I'm not sure how this would be done, but it would be neat if we could do a check to see if Jetpack's Mobile theme is active and if so, at least output the main blog feed instead of a blank page.

**Comment by jameskoster** [comment]
IMO it should mimic the desktop version and display products as well as the page content. Blog posts aren't going to be much use on a WooCommerce site. A lot of them don't even run a blog.

It would be nice to pull in the product template tags, I can't find the code for the mobile theme in Jetpack though to see if that's possible.

Tbh, I generally recommend _not_ using this feature. Storefront is responsive so there shouldn't really be any need.

**Comment by jameskoster** [comment]
Gonna close this for now. For tidiness.
