### ISSUE TITLE
Shortcodes not outputted within Text Widgets

### ISSUE THREAD

**Issue by stuartduff** [woothemes/storefront#209]
When adding short-codes to a text widget in the header area for example the short-code is not outputted. 

Filtering the text widget output below works to allow short-codes to display.

```
add_filter( 'widget_text', 'do_shortcode' );
```
**Before filter**
![ii_14ebc61ab9f76e7b](https://cloud.githubusercontent.com/assets/1190565/8860131/bb12df0c-3179-11e5-8941-ec1c5a6be4d2.png)

**After filter**
![ii_14ebc61affc404a8](https://cloud.githubusercontent.com/assets/1190565/8860135/c1a6eb88-3179-11e5-99f1-26e633e6f438.png)

Maybe worth adding to the theme?

**Comment by jameskoster** [comment]
imo this is plugin territory and shouldn't be forced upon people as a theme feature.

I usually recommend this one: https://wordpress.org/plugins/allow-shortcode-in-text-widgets/
