### ISSUE TITLE
@opacity markers are not compiling into valid css

### ISSUE THREAD

**Issue by indietravel** [woothemes/storefront#213]
Error: Invalid CSS after "... alpha(opacity=": expected expression (e.g. 1px, bold), was "@opacity * 100);"
        on line 1982 

I'm guessing @opacity * 100 should be doing some maths when compiled in less.

**Comment by indietravel** [comment]
Sorry, this issue is for Superstore theme; not Storefront. Woo staff, what's the best way to report that?

**Comment by jameskoster** [comment]
@indietravel I'll open issue on our private repository for that theme.

Thanks for reporting :-)

If you don't mind, I'd like to ask you why you chose Superstore over Storefront?

**Comment by indietravel** [comment]
Hi James, this project was started years before Storefront was even a dream... I think we launched it on Superstore 1.0!

**Comment by jameskoster** [comment]
OK thanks for letting me know :-)
