### ISSUE TITLE
Shop sorting texts getting double lines 

### ISSUE THREAD

**Issue by mkrdip** [woothemes/storefront#216]
On Chrome & Opera browsers, the shop sorting options are double line if the texts line is slightly big. On Firefox it shows fine. 

Screenshot (Chrome): 
![image](https://cloud.githubusercontent.com/assets/3819579/9343963/330943f4-4627-11e5-8e70-e7c1fd10e8bc.png)

Screenshot (Opera): 
![image](https://cloud.githubusercontent.com/assets/3819579/9343993/65e6f6a4-4627-11e5-892b-82e76f6de96d.png)

`.storefront-sorting select {
    width: 9.505em;
}` at woocommerce.scss is causing this. If width is set as `width: auto` it gets fixed both on Chrome & Opera. Check my PR please.

**Comment by JJ24GH** [comment]
The same thing happens on iPad in both portrait and landscape views.

**Comment by jameskoster** [comment]
Fixed in https://github.com/woothemes/storefront/pull/217
