### ISSUE TITLE
Links on mobile devices require double taps

### ISSUE THREAD

**Issue by tiagonoronha** [woothemes/storefront#218]
Reported here: https://wordpress.org/support/topic/links-on-mobile-devices-require-double-taps?replies=7

I tested on my iPhone with Safari. I had to double tap on the navigation toggle for the menu to show up and also double tap on any of navigation links to navigate to them.

**Comment by jameskoster** [comment]
Couldn't replicate this for menu items, but it seems anything with the `.button` class is affected.
