### ISSUE TITLE
Double Tap on Mobile Before Navigation Expands

### ISSUE THREAD

**Issue by RiaanKnoetze** [woothemes/storefront#222]
Link to ticket: https://woothemes.zendesk.com/agent/tickets/328187

Customer reports that users need to double tap the "Navigation" bar in responsive mode before it expands. While I wasn't able to reproduce that on my iPhone 6 / Safari (or the Browserstack simulators), @mikeyarce did do some crowdsourced testing in #happiness - with testers reporting that they experienced the same on a variety of phones.

**Comment by el-presidente** [comment]
I experience the same issue on my 6+ with Safari ingognito. The menu won't open before the 2nd click and also the menu items I have to click twice.

**Comment by tiagonoronha** [comment]
Hey guys,

This has been already reported in #218.

Closing!
