### ISSUE TITLE
'WooCommerce Recently viewed Products' Widget not appearing on the sidebar or the Footer widget areas

### ISSUE THREAD

**Issue by spraveenitpro** [woothemes/storefront#223]
The 'WooCommerce Recently viewed Products' Widget  does not appear to load on frontend after being added to the Footer or the sidebar widget areas.  Using StoreFront version 1.5.0 and WooCommerce version 2.4.6. Tested this on two separate environments.

**Concerned ticket**

https://woothemes.zendesk.com/agent/tickets/328220

**CC**

@stevetested @BFTrick @tommyshellberg @slash1andy

**Comment by BFTrick** [comment]
Hey @jameskoster let me know if you need anything changed on the WC side.

**Comment by jameskoster** [comment]
Seems to be working fine for me? Did you actually look at some products after adding the widget? xD

**Comment by jameskoster** [comment]
Re-open if necessary.
