### ISSUE TITLE
Storefront Parallax Hero issue on iPad/tablet

### ISSUE THREAD

**Issue by JJ24GH** [woothemes/storefront#224]
The parallax hero image is not responsive when viewing on my iPad/safari in either portrait or landscape view. When viewing on desktop using safari and shrinking my browser window, however, it is responsive.

Thanks.

![img_2137](https://cloud.githubusercontent.com/assets/14097362/9642069/2baefd58-5188-11e5-8e36-b818b49ff7fb.PNG)

**Comment by jameskoster** [comment]
I've opened this issue on our private Parallax Hero repo. Thanks for reporting.

**Comment by jameskoster** [comment]
FYI I've just deployed an update which should fix this.
