### ISSUE TITLE
Improved integration with Variation Swatches & Photos needed

### ISSUE THREAD

**Issue by MindyPostoff** [woothemes/storefront#225]
When using Storefront with our Variation Swatches and Photos extension replaces the attribute dropdowns for variable products with swatches/photos. When a default variation is set, Storefront doesn't highlight the swatch/photo at all, but it should.

![](http://cld.wthms.co/UOTe/4lcd6DUX+)

**Comment by jameskoster** [comment]
@MindyPostoff latest Storefront? It's working just fine here. The swatches should be 50% transparent, then 100% when hovered/selected.

**Comment by MindyPostoff** [comment]
@jameskoster In this example, the red variation swatch should be selected as a default. In terms of feedback, it's confusing for the user because there is no difference between the red and blue variations as they're both displaying as 100% transparency. If manually selected, I believe there is a border around the swatch. So, as it's already selected as a default when the product page loads, it might be good to display the border. 

The yellow swatch is sold out, so it should remain non-selectable and transparent at 50% or less  :)

**Comment by jameskoster** [comment]
I've improved the styling to make the selection clearer: https://cloudup.com/c7mi0lcgnnx

Unfortunately there's no class added for unavailable variations so they can't be given a unique style. That would be a nice enhancement. I'll open an issue :-)
