### ISSUE TITLE
Bug in storefront version 1.5.0

### ISSUE THREAD

**Issue by healiny** [woothemes/storefront#230]
![header](https://cloud.githubusercontent.com/assets/11602443/9815942/7bbbeba0-58a2-11e5-9343-116a2dbabdb1.jpg)
![4-bottoms](https://cloud.githubusercontent.com/assets/11602443/9815950/8ae518d6-58a2-11e5-989c-7d1d3924b1b1.jpg)

I use storfront theme vesion 1.4.6 
I use my own child theme - storfont-child

Update to version 1.5.0 has a problem with CSS files 
All display the site messed up.

I saw the file rtl.css to become a style-rtl.css 
Something also changed in style.css.

I need your help in order that I can upgrade. 
Thank you.

**Comment by jameskoster** [comment]
Can you please post this on the wordpress.org forums and include a URL?

**Comment by healiny** [comment]
I do not understand why?
In forum I supposed to ask people, and this is a bug in the update version ..
WooTheme changed the files - style and Rtl.css
And probably more files, and I want to find out what exactly.

**Comment by jameskoster** [comment]
Many files were changed, you can see each of the commits that went into 1.5.0 here: https://github.com/woothemes/storefront/compare/version/1.5.0...master

I closed this as it's not an issue I've seen reported elsewhere so I assume there's a problem in your setup. Please provide a URL and I can investigate further.

**Comment by healiny** [comment]
http://shop.bentwood.co.il/

**Comment by jameskoster** [comment]
I see you've rolled back a version. Do you have a staging setup somewhere for me to see what's happening with 1.5.0?

**Comment by healiny** [comment]
I will copy the site and provide you a website URL. 
I can do it later, in a few hours.

**Comment by healiny** [comment]
Hello jameskoster
I'm Duplicate my site - http://shop.bentwood.co.il/
To this URL - http://shop.bentwood.co.il/storefront-1.5.0/

<b>I researched and I found three problems:</b>
1. The file rtl.css in storefront theme deleted, and have a new one - style-rtl.css
    (I need to change the link - @import url("../storefront/rtl.css"); <b>to</b> 
                                               @import url("../storefront/style-rtl.css");
2. The site does not refer to a file - /storefront-child/style.css
    I can set the file in /storefront-child/function.php, but WordPress should detect it automatically.
3. After I arrange all the files in storefront-child/functions.php <b>and</b> storefront -child/rtl.css
    part of the site seem aligned to the left (LTR) because of WooTheme changed the file style-tl.css

Thank's Eyal

**Comment by jameskoster** [comment]
OK, I see the issue.

**Comment by healiny** [comment]
Did you report it? - In Wootheme and in the Forum?
Have a suggestion for me what to do?
Should I arrange it and upgrade the theme?

**Comment by jameskoster** [comment]
I will fix :-)

**Comment by healiny** [comment]
Thanks :+1: 
What do you mean - Then you can take the fix from here?
From where?

**Comment by jameskoster** [comment]
From Github :-)

**Comment by healiny** [comment]
How do I know where the link, and when?
You can write to me here?

**Comment by healiny** [comment]
Sorry, I dont Understand.

**Comment by jameskoster** [comment]
Replace your version of storefront/inc/functions/setup.php with this one:

https://github.com/woothemes/storefront/blob/e10672dfbe8d4122933c3ced61495dd85c82a713/inc/functions/setup.php

Let me know if that works.

**Comment by healiny** [comment]
Hi, 
This still did not solve the issues
this is site URL - http://shop.bentwood.co.il/
this is site 1.5 URL - http://shop.bentwood.co.il/storefront-1.5.0/

<b>I researched and I found some problems:</b>
The system still does not recognize the files - /storefront-child/style.css, /storefront-child/rtl.css

<b>I found the place:</b>
In function storefront_scripts - in else - <b>change this</b>
wp_enqueue_style( 'storefront-child-style', get_stylesheet_uri(), '' );
<b>to</b>
wp_enqueue_style( 'storefront-child-style', get_stylesheet_uri() . '/style.css', '' );

<b>but there have sum problems..</b>
1. The system still not recognize the file - /storefront-child/rtl.css
2. part of the site seem aligned to the left (LTR) because of WooTheme changed the file style-tl.css
    I need to cancel the changes in style-tl.css (Because I have defined my on RTL)

Thank's Eyal

**Comment by jameskoster** [comment]
I just double checked and the child themes stylesheet is definitely loaded. `get_stylesheet_uri()` includes a reference to style.css.

I also created an rtl.css file in my test child theme and it was loaded correctly.

It sounds like you're building your own RTL stylesheet. I'm not really sure why though, Storefront 1.5 should work fine with RTL languages without any modifications.

If there's an issue with our RTL implementation it would be better for you to report that specifically so we can fix it. It's hard to fix anything when you're working with your own custom RTL implementation as I don't have access to that personally.

**Comment by healiny** [comment]
I built my site in an earlier version of the storefront
If you build a site with child theme and RTL in an earlier version and then upgrade to version 1.5 you will encounter a lot of problems because of the changes you have made.

Certainly when the new site, maybe will work well ..  
but upgrade versions should work smoothly,
For it created the child theme, does not it?

For me, the problems still exist despite that I set the child theme according to the WooTheme and WordPress instructions, and right now I can not upgrade versions of store front.

**Comment by jameskoster** [comment]
> If you build a site with child theme and RTL in an earlier version and then upgrade to version 1.5 you will encounter a lot of problems because of the changes you have made.

That's because old versions of Storefront didn't actually include any RTL support. If you just remove the rtl.css file you created it should work a lot better.

**Comment by healiny** [comment]
Still does not work well
In the meantime, I found other problems that created in the customize in Wordpress.
I attached the file that you are able to get an impression.

By the way, thank you for taking care of us with compatibility with RTL :-)

![header-background-color](https://cloud.githubusercontent.com/assets/11602443/10021803/725bd0c6-6152-11e5-8475-42a0c567a779.jpg)

**Comment by jameskoster** [comment]
That looks much better. 

The RTL implementation doesn't touch the Customizer though. There's no reason why those settings wouldn't work.

Try deactivating plugins to check for a conflict.

**Comment by healiny** [comment]
I deactivating plugins to check for a conflict, and no conflict.
Those settings dosn't work.

I think the problem stems from changes you have made in RTL and also in style.css.
I saw that you are set the header color in style.css, and it overrides Those settings.

**Comment by jameskoster** [comment]
I just tested this and it works fine for me: https://cloudup.com/cqVK9So1whl

**Comment by healiny** [comment]
You tried to save and see how it looks in the real site?
At first it seemed OK, and then changes.
This happens because of what I showed you in FireBug.

**Comment by jameskoster** [comment]
Yes I saved and it was fine.

**Comment by healiny** [comment]
But still have problem

See my website and what happened to him after the upgrade
And in the fire bug.
To me it seems wrong ..
