### ISSUE TITLE
Mini cart background

### ISSUE THREAD

**Issue by mjepson** [woothemes/storefront#232]
It seems like the background for the mini cart dropdown is off with my settings.

![bug](https://d1zjcuqflbd5k.cloudfront.net/files/acc_68968/WHPI?response-content-disposition=inline;%20filename=Screen%20Shot%202015-09-19%20at%2011.08.19.png&Expires=1442654095&Signature=Strhk7OIhAShF2PYPpnxt3BzzX28IYkdX3NpxR1czJUVFYJA~KTjXQak1aibP-q5va~S9KDyKlkNKixR0~evTs~Hx~5vdfInKSu0VKHOsathXzNq6nx~7vdCwxPWQ6s8SdoBTsOIanDjuRhlnAaUsmZn0kX33kyUC7xkd~IKe5U_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

General: http://d.pr/i/1el6p/5f8lSUiE
Tax: http://d.pr/i/140CE/2U8E4D3l

Can be tested here: http://104.131.116.80/magnus/shop/

**Comment by jameskoster** [comment]
@mjepson screenshot seems to be missing? The Mini Cart looks ok here: https://cloudup.com/cNorPDeYT8Q

**Comment by mjepson** [comment]
Tried again http://d.pr/i/5M0H/4oGXcsG0

**Comment by jameskoster** [comment]
Ah right, that's the scrollbar. What scrollbar settings do you have here: https://cloudup.com/cZvhGDFDkZQ ?

I tried all 3 options and wasn't able to get it to persistently display like that, when there are not enough items in the cart to make it scroll.

You definitely have Storefront latest as well, right?

**Comment by mjepson** [comment]
I’ve got this http://d.pr/i/1j6h1/2qiN8nVJ

I’m on 1.5.1 

-- 
Magnus Jepson
http://www.jepson.no
Twitter: @mjepson

On 22 Sep 2015 at 12:21:42, James Koster (notifications@github.com) wrote:

Ah right, that's the scrollbar. What scrollbar settings do you have here: https://cloudup.com/cZvhGDFDkZQ ?

I tried all 3 options and wasn't able to get it to persistently display like that, when there are not enough items in the cart to make it scroll.

You definitely have Storefront latest as well, right?

**Comment by jameskoster** [comment]
Strange, that's exactly what I have and it's fine in Chrome and FF.

You're on FF right? And latest Yosemite?

**Comment by mjepson** [comment]
Chrome, latest Yosemite

-- 
Magnus Jepson
http://www.jepson.no
Twitter: @mjepson

On 22 Sep 2015 at 12:45:34, James Koster (notifications@github.com) wrote:

Strange, that's exactly what I have and it's fine in Chrome and FF.

You're on FF right? And latest Yosemite?

**Comment by jameskoster** [comment]
OK last question, mouse or trackpad?

I've a trackpad and an old usb mouse plugged in. Perhaps you're using a magic mouse?

**Comment by mjepson** [comment]
Normal Logitech M705 mouse :)



On 22 Sep 2015 at 12:51:40, James Koster (notifications@github.com) wrote:

OK last question, mouse or trackpad?

I've a trackpad and an old usb mouse plugged in. Perhaps you're using a magic mouse?
