### ISSUE TITLE
Cart icon interfers with items text

### ISSUE THREAD

**Issue by el-presidente** [woothemes/storefront#236]
The cart icon is on top of the text 'items' when the amount is four digit and currency is DKK:

![skaermbillede 2015-09-24 kl 09 46 50](https://cloud.githubusercontent.com/assets/937382/10068030/62ae00f4-62a1-11e5-87a6-d5ee45bd9e21.png)

**Comment by jameskoster** [comment]
The padding on the button looks a little off, could you share a URL?

Ultimately though, there's always a chance of this happening. EG if a visitors has a very large total in their cart they will see this problem.

In these instances it's probably best to just hide that icon.

**Comment by el-presidente** [comment]
Yes I guess so - I think the trouble being our currency in Denmark is written DKK which is more wide than say £,€ or $ together with very expensive products :)

http://5.1.75.105/

**Comment by jameskoster** [comment]
Yeah I'd definitely just remove the icon in this case.
