### ISSUE TITLE
Unnecessary header, very similar to sidebar. Menu buttons, not customizable. 

### ISSUE THREAD

**Issue by partounian** [woothemes/storefront#239]
![screen shot 2015-09-25 at 3 44 10 pm](https://cloud.githubusercontent.com/assets/2541595/10113780/05671956-639d-11e5-8a7f-d6be327391ff.png)
I'm not sure why, but they've broken a lot. I have tested this with my child theme, my updated 1.5.1 (through WP backend), and through manually installing a new copy of 1.5.1 from the download link for the zip.

Note: I have cropped the top are off with the logo and what not, but this is what displays when you attempt to customize the theme. Yes, the buttons disappear.

**Comment by jameskoster** [comment]
Hi,

Looks like you have some widgets in your header widget region. Just remove those via Appearance > Widgets.

You can add menu items via Appearance > Menus.
