### ISSUE TITLE
Customizer - Layout Section

### ISSUE THREAD

**Issue by DustinHartzler** [woothemes/storefront#240]
The Layout section of the Customizer looks a bit wonky on Windows Chrome and Firefox

![image](https://cldup.com/JhPcQiKC05.PNG)

**Comment by jameskoster** [comment]
Think this might be a WP style thing. Which version are you using? Looking fine here on 4.3.1; https://cloudup.com/cOMxr3AM7Ux

**Comment by DustinHartzler** [comment]
It might be related to the **Storefront WooCommerce Customiser** plugin. I'm waiting to hear back. If it is, I can report the bug there :)

**Comment by jameskoster** [comment]
I think this is likely the WP version. Please also check they're running the latest version.

**Comment by jameskoster** [comment]
Going to close this one as I've not seen it reported elsewhere and cannot reproduce. If you figure out the exact cause please feel free to re-open.
