### ISSUE TITLE
Integration with Storefront Mega Menus

### ISSUE THREAD

**Issue by tiagonoronha** [woothemes/storefront#243]
Mega Menus outputs a div with a `smm-mega-menu` class inside of respective parent menu item. This is how the structure looks like:

```
<ul id="menu-primary" class="menu nav-menu" aria-expanded="false">
	<li id="menu-item-X" class="menu-item menu-item-has-children menu-item-X smm-active">
		<ul class="sub-menu">
			<li>
				<div class="smm-mega-menu">
					{ .. }
				</div>
			</li>
		</ul>
	</li>
</ul>
```

Currently the CSS for the dropdowns is conflicting with the output of the widgets in the `smm-mega-menu` div. Many widgets use `<ul>` and `<li>` to display their content.

I believe we can solve this by being more specific in the CSS that we use to target the nav items.

Quick examples:

`.main-navigation ul.sub-menu` instead of `.main-navigation ul`.

`.main-navigation ul.sub-menu li.menu-item` instead of `.main-navigation ul li`.

/cc @jameskoster

**Comment by jameskoster** [comment]
Don't think we need to add anything else to core.
