### ISSUE TITLE
Child Theme Shows Incorrect Version

### ISSUE THREAD

**Issue by DustinHartzler** [woothemes/storefront#244]
I think this is a Storefront issue, as it appears when using Galleria, Deli, or ProShop.

When you look at the system status, it thinks that there is a newer version of the child themes available, when the version 1.5.1 is the version number for Storefront:

<img width="691" alt="screen shot 2015-10-09 at 9 30 48 am" src="https://cloud.githubusercontent.com/assets/2293077/10394986/97bf06b2-6e68-11e5-8392-59f9a60f6564.png">

**Comment by WPprodigy** [comment]
May be a system status report bug: https://github.com/woothemes/woocommerce/blob/5917ff15ba734b32aca7bc97bb873d81164afb15/includes/admin/views/html-admin-page-status-report.php#L594-L604

**Comment by jameskoster** [comment]
This will be a WooCommerce issue, probably not accounting for child themes. Please open an issue there :-)
