### ISSUE TITLE
Reset Variations - Needs styling

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/storefront#247]
Default: http://cld.wthms.co/1kvvI/1DiMmEVV

This should be dropped down to below the last variation. So like this: http://cld.wthms.co/1iB87/1XnxVC7n

```
a.reset_variations {
display: block;
}
```

**Comment by jameskoster** [comment]
Problem with `display: block;` here is that the element will then take up space even if it's hidden. I think just adding a margin is sufficient.
