### ISSUE TITLE
Norwegian Translations Broken

### ISSUE THREAD

**Issue by scottbasgaard** [woothemes/storefront#250]
Yo @jameskoster not sure this is the place or I can open it up on transifex.

nb_NO.mo and nb_NO.po are both empty with no translations but nb.mo and nb.po are correct.

**Comment by jameskoster** [comment]
Hey man, translations are all done on .org now; https://translate.wordpress.org/projects/wp-themes/storefront

Is that one borked too?

**Comment by scottbasgaard** [comment]
@jameskoster ah okay, forgot about that transition!

So not sure where the exact issue comes from but you'll see:

Correct locale string nb_NO is empty:
http://themes.svn.wordpress.org/storefront/1.5.1/languages/nb_NO.po

This has what's needed though:
http://themes.svn.wordpress.org/storefront/1.5.1/languages/nb.po

**Comment by jameskoster** [comment]
@scottbasgaard honestly I'm not sure. This needs someone on the .org translation team to look at it I guess. I'm not sure who to poke xD Any ideas?

Gonna close the issue here though as it's not a Storefront code issue.

**Comment by scottbasgaard** [comment]
:+1:
