### ISSUE TITLE
Improving font loading

### ISSUE THREAD

**Issue by partounian** [woothemes/storefront#253]
Could improve font loading by setting a fallback font during initial load and caching the font.

Useful links:
https://github.com/bramstein/fontfaceobserver

Beginning at the "Enabling fonts when they’re really loaded" is where the useful information begins
https://www.filamentgroup.com/lab/font-events.html

**Comment by jameskoster** [comment]
We only load FontAwesome and the tiny WooCommerce star icon font. There's not really a fallback for either so I'm not sure this is worth it.
