### ISSUE TITLE
Ajax layered navigation issue

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/storefront#258]
When Ajax layered nav is active, Storefront's products filter does not work.

Seems like it could be an issue with either Storefront or the extension, but this only occurs on storefront and not on the default themes.

https://github.com/woothemes/woocommerce-ajax-layered-nav

Update: This product filter - http://cld.wthms.co/16yG9/16kTnXPv

**Comment by jameskoster** [comment]
Seems to be due to the fact that Storefront has the sorting `select` both above and below the products. There's no reason a theme shouldn't be able to do this and it works fine with Vanilla WooCommerce. I suggest opening an issue on the AJAX layered nav repo as the issue most likely lies there somewhere.

**Comment by jameskoster** [comment]
@WPprodigy just took a look at the AJAX layered nav code. It wraps products in a `#products` but because of the unique Storefront sorting section it gets messed up (incorrect priorities). Not sure if that's related. Digging further.

**Comment by jameskoster** [comment]
Adding priorities [here](https://github.com/woothemes/woocommerce-ajax-layered-nav/blob/master/ajax_layered_nav-widget.php#L126-L127) fixes the wrapping issue, but the sorting still doesn't work.

Need the extension author to shed some light on this.

**Comment by djwienhold** [comment]
Thanks guys. Pushing an update to the aln repo shortly.

**Comment by jameskoster** [comment]
Noice!

**Comment by WPprodigy** [comment]
Tested the patch, all seems good.
