### ISSUE TITLE
Theme seems to Stop working IE 8 and below

### ISSUE THREAD

**Issue by quasel** [woothemes/storefront#264]
https://wordpress.org/support/topic/wootheme-storefront-error-displaying-in-ie8?replies=1
Same for me - did someone look into it? Because IE8&below has still a market share around about 5% 

I wouldnt expect it to fully work but currently it's very bad - maybe at least display a warning and get users to upgrade ^^

I know IE to be gone would be a dream but ...

**Comment by jameskoster** [comment]
Storefront doesn't and has never supported IE8. Sorry about that. This is mainly due to IE8s lack of support for HTML5. Installing an HTML5Shiv will probably fix most of the issues you're having.
