### ISSUE TITLE
Variable products with attributes that have "Visible on the product page" are not displayed.

### ISSUE THREAD

**Issue by partounian** [woothemes/storefront#266]
As stated the dropdowns/options for attributes are not displayed unless they have "Used for variations" checked. Shouldn't they display as a single option in a dropdown menu?

**Comment by WPprodigy** [comment]
Hi @partounian,

I'm not sure I understand. You want to use attributes in a variation dropdown without checking "used for variations"? If you only have "display on product page" checked, then those attributes are just for show in the front-end.

Either way, this is definitely not an issue with Storefront, and I'm pretty sure there isn't a WooCommerce issue here either.

For support, please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooThemes Support](http://support.woothemes.com) page.

**Comment by partounian** [comment]
Can you specify what you mean by "just for show"?  Because I would like to have the dropdown even though it's one option just to help the customer out.

**Comment by jameskoster** [comment]
Closing this as it's not a Storefront issue.
