### ISSUE TITLE
No support for Sensei declared

### ISSUE THREAD

**Issue by smcjones** [woothemes/storefront#268]
On the website, Storefront is now the primary theme recommended for Sensei. However, Sensei support is not declared for Storefront. I tested the integration and it seems like it does integrate nicely. Just wanted to give you a heads up!

**Comment by jameskoster** [comment]
> On the website, Storefront is now the primary theme recommended for Sensei.

Where have you seen this? Afaik that is not our official stance on this :-)

**Comment by smcjones** [comment]
Fair enough. I know you guys are splitting up so it could just be a consequence of the move. Appreciate any direction you can give me (although I'm making good headway with this great theme).

http://www.woothemes.com/products/sensei/

Follow the link:

> Need a design for your Sensei-powered online classes? View our Sensei themes.

Meanwhile, the Scholar child theme link is broken and redirects to the *Retired Theme* page.

http://www.woothemes.com/products/scholar

**Comment by jameskoster** [comment]
I know the Sensei team have been working on how it looks in Storefront for 1.9. You can keep up to date with developments over here; https://github.com/woothemes/sensei
