### ISSUE TITLE
stock color

### ISSUE THREAD

**Issue by jameskoster** [woothemes/storefront#269]
in stock = green
out of stock = red

Inherit colors from messages.

**Comment by nishitlangaliya** [comment]
@jameskoster, should I try and do the pull request for the same ?

**Comment by jameskoster** [comment]
@nishitlangaliya you can if you want :)

**Comment by nishitlangaliya** [comment]
@jameskoster, Sure Thanks will update you for the same... :)

**Comment by nishitlangaliya** [comment]
@jameskoster , I have applied the color code to in stock and out stock message and done the pull request https://github.com/woothemes/storefront/pull/270 for the same. please review it when you get a chance 

Thanks :)

**Comment by nishitlangaliya** [comment]
@jameskoster , I am still getting message during pull request 'can’t automatically merge' though I had taken fresh clone get pull from master and created branch from it. do I need to delete all my old branch  ?

**Comment by jameskoster** [comment]
@nishitlangaliya yes you will probably have to start again, you can't have had the latest scss files.

**Comment by nishitlangaliya** [comment]
@jameskoster Thanks for reply . I will do the same as you sugeested and will do the PR.

**Comment by nishitlangaliya** [comment]
@jameskoster  I had done the pull request https://github.com/woothemes/storefront/pull/272 without any conflict please check for the same.

Thanks :)

**Comment by tiagonoronha** [comment]
@nishitlangaliya this looks good, thanks! :) Just a suggestion, to make the SASS easier to follow, perhaps change it to:

```
&.in-stock {
	color: $success;

	&:before {
		content: "\f118";
	}
}

&.out-of-stock {
	color: $error;

	&:before {
		content: "\f119";
	}
}
```

After that I'll be happy to merge this. :)

**Comment by nishitlangaliya** [comment]
@tiagonoronha  Thanks for your suggestions as per your suggestion I have done the changes and done PR - https://github.com/woothemes/storefront/pull/274 for the same. can you please review it when you geta a chance :)

**Comment by tiagonoronha** [comment]
Looks good, merged!

Thanks, @nishitlangaliya.

**Comment by nishitlangaliya** [comment]
@tiagonoronha Thanks  :)
