### ISSUE TITLE
Child-theme style-rtl.css doesn't seem to be loaded after upgrading to 1.5.3

### ISSUE THREAD

**Issue by S4Mi** [woothemes/storefront#273]

**Comment by mattyza** [comment]
@S4Mi Perhaps try renaming  `style-rtl.css` to `rtl.css`? `rtl.css` is [the standard for adding RTL support](https://codex.wordpress.org/Right-to-Left_Language_Support) to WordPress themes. :)

**Comment by S4Mi** [comment]
nope, still not working.
