### ISSUE TITLE
Shipping Multiple Addresses Styling

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/storefront#279]
http://www.woothemes.com/products/shipping-multiple-addresses/

Here is the default styling for Shipping Multiple Addresses in Storefront: http://cld.wthms.co/19KUG/2scYNOq7. That is just with two packages. Gets a bit worse when you add more.

Maybe just take away the float and give them full width? http://cld.wthms.co/17we9/2PNdfAmo

**Comment by jameskoster** [comment]
Oooooo, ugly. Yeah, I like your solution. We should remove their styling as well, those boxes make make each address take up more space than is necessary. A simple border between each would be sufficient.

You wanna send a PR? :-)

**Comment by WPprodigy** [comment]
Ehh, me and CSS are at a current disagreement. We aren't getting along so well ;p

**Comment by BurlesonBrad** [comment]
Hey @WPprodigy I wanna take a spin at fixing another "bug".  Can I take a crack at this one too?

**Comment by WPprodigy** [comment]
@BurlesonBrad Go for it! 

I think you'll want to create a new scss file here: https://github.com/woothemes/storefront/tree/master/inc/woocommerce/css

And then add it to be compiled here: https://github.com/woothemes/storefront/blob/626d8c52be2f9f1ba86a59733ebe575c19c9fd4b/Gruntfile.js#L52

**Comment by jameskoster** [comment]
@BurlesonBrad awesome that you're keen to jump on this :-) Any idea when you might look at it? I only ask as I'm quite keen to close a bunch of these issues this week and prepare a release before the holidays.

**Comment by BurlesonBrad** [comment]
Ok, @jameskoster , lemme take my "learning curve" for a spin here, and see if I can get on it tonight ~ central time.
( I gotta find a client's CC somewhere so I can snag a copy of that multiple address extension )
Do I also need to see some form of Storefront 1.6 beta...?

**Comment by jameskoster** [comment]
@BurlesonBrad just use the latest master branch :)

**Comment by BurlesonBrad** [comment]
![storefront-mulitple-addresses](https://cloud.githubusercontent.com/assets/6208757/11509729/6e4c9f9c-9825-11e5-8e7b-6f3c3bf8ef17.png)

Am I missing something @WPprodigy ?  I want to grow my "bug-fixing-skills", but this is looking pretty good to me :+1:

**Comment by WPprodigy** [comment]
Looks good to me. I think @jameskoster wanted to also try just removing all the styling in that area. So including the grey box if it still looks good.

Also, be sure to test with the default SF layout when there is a sidebar on the checkout page. The order review area is much thinner, and we should probably have each address on it's own line at that point.

**Comment by BurlesonBrad** [comment]
oh #whoops 
back at it again w/ sidebar on... standby

**Comment by BurlesonBrad** [comment]
See, this is the point where I get totally CORN-fused.  If you add a style for one setting ~ let's say "no-sidebar"..... that's fine and dandy.  But now ...how to get the same style to behave correctly when someone chooses to have a sidebar? ....or how to get the same style to show up once someone chooses another layout's option?
![shipping_addresses](https://cloud.githubusercontent.com/assets/6208757/11516482/0f79fe00-9849-11e5-9e78-5bfe279b701a.png)
That's where I get a bit "lost".  I definitely know it's possible.  And, (pardon my while I brush up on my CSS TreeHouse course.  Ok, I'm back) shouldn't one of those classes and divs be 100% and then inherit (ed) into smaller divs ~ 96%, then 94%, then 90% ...things like that?

@jameskoster don't hold 'ya breath :-)

**Comment by jameskoster** [comment]
Np @BurlesonBrad, we'll look into it :)
