### ISSUE TITLE
Best practice to customize storefront?

### ISSUE THREAD

**Issue by montalvomiguelo** [woothemes/storefront#281]
[Storefront Child Theme](https://github.com/stuartduff/storefront-child-theme) __or__ [Theme Customisations Plugin](https://github.com/woothemes/theme-customisations)  ?

**Comment by jameskoster** [comment]
@montalvomiguelo depends what you're doing really. 

I'd generally recommend using a plugin as it gives you the freedom to switch to a different child theme (say you wanted to use one of our [commercial child themes](http://www.woothemes.com/product-category/themes/storefront-child-theme-themes/) for example) without losing any of your customizations. You could feasibly put each customisation in it's own individual plugin as well which can be handy for debugging / quickly enabling/disabling features.

The only drawback to using that plugin is that it doesn't allow you to perform non-top-level template overrides (things like footer.php, content.php etc). But given how Storefront is built there's not really ever a need to override those templates. 

So yeah, nothing will go wrong if you use a child theme, but unless you need specific template overrides then I think the plugin is the better approach.
