### ISSUE TITLE
Make the order review on checkout sticky

### ISSUE THREAD

**Issue by jameskoster** [woothemes/storefront#285]
http://ideas.woothemes.com/forums/275029-storefront/suggestions/10778421-storefront-checkout-button-not-available-at-checko

Will need integration with the Checkout Customiser extension as well.

What do you think @tiagonoronha? Should we do this in core?

**Comment by tiagonoronha** [comment]
How about something like the "Storefront Sticky Add to Cart" extension? But yeah, if it helps a lot of people, it should probably be in core.
