### ISSUE TITLE
Add review hover 

### ISSUE THREAD

**Issue by jameskoster** [woothemes/storefront#287]
The hover styles for the stars are activated even when the mouse cursor is off to the right of the stars: In other words, the user is able to adjust the star rating without hovering over a star.

Gif: http://cld.wthms.co/16Vra/4n0oMVHh

**Comment by RiaanKnoetze** [comment]
The ability to actually click on a star is also not working : http://cld.wthms.co/1fhEC/34JWZo31

**Comment by jameskoster** [comment]
@RiaanKnoetze sure you have the latest everything and have compiled Storefront css/js? Not seeing that issue here.
