### ISSUE TITLE
Search Console with hAtom microformat error 

### ISSUE THREAD

**Issue by neltseng** [woothemes/storefront#290]
Hi, does anyone who has the same issue that structured data by Google Search Console shows some hAtom microformat missing below just on every single page in Strorefront ?
* Missing: author
* Missing: entry-title
* Missing: updated

![screen shot 2015-12-08 at 9 17 43 am](https://cloud.githubusercontent.com/assets/6985904/11645546/5477dad0-9d90-11e5-8358-e7cdf1a339fb.png)

**Comment by jameskoster** [comment]
Yeah the issue here is that pages do not display an author or a published date. To fix this you'd need to do so which doesn't really make sense imo. We wont be adding this to core but you can easily customise this via child theme if you want to.
