### ISSUE TITLE
Strange vertical line above archive product image and below price when item clicked

### ISSUE THREAD

**Issue by ChangePlaces** [woothemes/storefront#293]
On an archive page, if you click on a product, you see a strange vertical line above the product image, and below the price when clicked. Tracing through, it seems to be somewhere about the template content-product. This is driving me insane as I don't think it's totally a CSS issue. From what I can see, it's one of those hard-to-track-down problems where a space in a php file is knocking the html around.

However, I have manage to discover that removing display:block from the product image and .price removes the lines.

**Comment by jameskoster** [comment]
This is the `outline` styles applied when the link is focussed and is an accessibility enhancement. You can read more about that here; https://www.woothemes.com/2015/03/storefront-1-4-2-now-more-accessible/

To remove it you'd need to add something like;

`ul.products li.product a:focus { 
outline: none !important; 
}`

Cheers

**Comment by ChangePlaces** [comment]
That's good to know - thanks
