### ISSUE TITLE
Star ratings on Storefont

### ISSUE THREAD

**Issue by jonpedlow** [woothemes/storefront#294]
Just a suggestion that on Storefront when a customer clicks on the stars to rate the product no star stays highlighted so they are unsure if has worked until the review has been left.

Maybe change the star icon when clicked on to make it obvious for them that it has been selected with this CSS?

p.stars a.active:before {
    content: "\e020";
}

Cheers

Jon

**Comment by jameskoster** [comment]
This is already fixed for the next release :-)
