### ISSUE TITLE
Rename header widget area to "Content Header" or similar

### ISSUE THREAD

**Issue by ChangePlaces** [woothemes/storefront#297]
The widget area "Header" is not in the header area, but is at the top of the content area, so maybe the region can be called "Content Header" or "Content Top" instead as it's more descriptive, paving the way for child themes to use header region names without mass confusion!

**Comment by jameskoster** [comment]
That's a fair point. I don't actually see many people even use this region. I wonder if we should consider removing it (replaced with a plugin).

Thoughts @tiagonoronha ?

**Comment by ChangePlaces** [comment]
Well, on second thoughts, it isn't in the content area but is instead top of the page (as the width includes the sidebar area as well), so, how about `Page Top` or just `Top of Page`. This type of full width is usually used for fullbar advertisements.

I think a widget that's at the top of the actual content area column will be darn useful, especially for text widgets for the woocommerce pages such as shop, cart, checkout which can be targeted with the widget_logic plugin.

I'm currently using the existing region as a block of welcome text because I have the front page set to the shop page.

**Comment by jameskoster** [comment]
@ChangePlaces 

> I think a widget area that's at the top of the actual content area column will be darn useful, especially for text widgets for the woocommerce pages such as shop, cart, checkout which can be targeted with the widget_logic plugin.

Isn't that what the current 'header' widget region is providing?

> I'm currently using the existing region as a block of welcome text because I have the front page set to the shop page.

You'd be better off just adding the welcome text to your shop page content?

> Other regions I think will be useful is a header bar that's above the actual existing menu header area. This could be used for flash sales, announcements etc at the top of the page. It seems a shame to have to use a plugin just to add that region!

Above the menu specifically could be tricky. But this plugin might be useful; https://en-gb.wordpress.org/plugins/storefront-top-bar/

> Also, a region that's at the bottom of the content just above the footer

https://en-gb.wordpress.org/plugins/storefront-footer-bar/ ;)

Another potential region we're currently considering is within the homepage template content.

**Comment by ChangePlaces** [comment]
I was thinking something like this
![storefront](https://cloud.githubusercontent.com/assets/302031/12204035/d42a7fce-b629-11e5-8e9b-9bca3a1fd187.png)

I forgot to add a content-bottom area below the content area!

**Comment by jameskoster** [comment]
Seems niche to me (like the current header widget region).

We could definitely create a plugin that provides these regions, though. One beneath the header, one above the content and one beneath the content.

@tiagonoronha any thoughts on this?

**Comment by ChangePlaces** [comment]
plugins shmugins. This is a theme issue!

**Comment by tiagonoronha** [comment]
@jameskoster Plugin. If you add one to the content top, you'll also want another one at the content bottom. Then you'll start thinking "why not also add one above the footer?" and "why not add one at the very top of the page?"

**Comment by ChangePlaces** [comment]
That's the whole point of a theme, no? To offer widget areas that allow it to be personalised. A plugin will add an additional CSS call to the page load and is just one main reason why it shouldn't be a plugin to add a few widget areas.

**Comment by jameskoster** [comment]
@ChangePlaces there's no way we'd add these regions to core. It makes much more sense for this to be a plugin. No CSS is required.
