### ISSUE TITLE
Put searchbar inside a widget?

### ISSUE THREAD

**Issue by ChangePlaces** [woothemes/storefront#299]
Hardcoding the search into the header like this feels dirty. Not all stores need / want a searchbar there, if at all. So, instead of hardcoding it like this, there should be some way of hiding it, or perhaps moving it around?

**Comment by jameskoster** [comment]
You can do this (and much more obviously) with the WooCommerce Customiser extension. Otherwise it's a 4/5 line snippet to remove it. We won't be adding options for tiny tweaks like this to Storefront core.
