### ISSUE TITLE
Cannot see checkout button

### ISSUE THREAD

**Issue by Nohcho** [woothemes/storefront#305]
After the 1.6.0 release, in my webshop I can no longer see the checkout button on the checkout review, which is now sticky.. It means that my customers can't checkout!!!
At first the button is visible, but after I choose a pickup point for shipping, the checkout review gets longer, and the button is no longer visible.

**Comment by Nohcho** [comment]
For now I have commented out that piece of code. I see you tried to avoid this same problem, but there is always this one scenario :)
If I get the time I will look at how it can be fixed.

Otherwise if any questions on how to reproduce, I will be glad to help.

**Comment by Nohcho** [comment]
It would be awesome if this feature could be disabled, because I personally do not like it.

**Comment by jameskoster** [comment]
Hmm, yeah in extreme edge cases it's possible for different payment methods to 'push' the pay button off-screen.

I'll make the height check a little less strict to try and account for that and add a filter so you can disable the feature altogether.

**Comment by nathanhere** [comment]
I still encounter this error -- Latest woocommerce installed
