### ISSUE TITLE
Checkout-review-order header is following while scrolling

### ISSUE THREAD

**Issue by el-presidente** [woothemes/storefront#306]
On desktop going to checkout, if I scroll down the review order box and its header will follow.

I have deactivated all plugins and running WC 2.5 and Storefront 1.6.

See http://land-dev.lightningbasehosted.com/kasse/ and ![skaermbillede 2016-01-19 kl 08 55 58](https://cloud.githubusercontent.com/assets/937382/12412882/da8512da-be8a-11e5-9cd2-c8bc98ebb5d3.png)

**Comment by el-presidente** [comment]
Just tried the new 1.6.1 with the same issue happening.

**Comment by jameskoster** [comment]
This is a feature :) It's so that the place order button is always visible to customers regardless of where they scroll.

There's a snippet to remove it in the docs; https://docs.woothemes.com/document/storefront-faq/

**Comment by el-presidente** [comment]
Cheers, though strange as I've never noticed it before..

**Comment by jameskoster** [comment]
It was added in 1.6. Check the changelog and the [release](https://github.com/woothemes/storefront/releases) page here at github before updating :)
