### ISSUE TITLE
Subcategory not showing

### ISSUE THREAD

**Issue by AbigailNeal** [woothemes/storefront#309]
Please can someone assist with this issue, we are using storefront as you can see from the attached link https://www.imaginediy.co.uk/product-category/decorative-items/. In the decorative items at the bottom Flowers and Resins as a subcategory is showing but is not showing on the drop down list when you hover over Decorative Items at the top.

**Comment by jameskoster** [comment]
Please post support requests on the wordpress.org support forums. Github is for bugs and enhancements :)

As a quick guess, check your Menus, maybe the new category wasn't added.
