### ISSUE TITLE
Strange star behaviour for reviews

### ISSUE THREAD

**Issue by esucces** [woothemes/storefront#310]
Check this video, me trying to select stars for the review:
https://drive.google.com/file/d/0BxFrFSfN2CAlMnZrMXF0M2JDbHc/view

Recorded from:
http://demo2.woothemes.com/storefront/product/happy-ninja/
http://demo2.woothemes.com/outlet/product/evolution-envy-mini-intel-core-i7-4790k-4-4ghz-nvidia-geforce-gaming-pc/

As a user i extect the stars to be filled, selection 4 should fill 4 stars etc.
So this seems to be a bug.

**Comment by tiagonoronha** [comment]
@esucces hi there! :)

See here: https://github.com/woothemes/storefront/issues/303

Fixed in 1.6.0.

We haven't updated our demo site yet.
