### ISSUE TITLE
Orders: really long orders don't fit in the window

### ISSUE THREAD

**Issue by mikeyarce** [woothemes/storefront#312]
I have a test subscription which uses a really long order.  In Storefront, when the Order "sticks" to the top, the actual Checkout button then becomes hidden.  Example:

![storefront-long-order](https://cloud.githubusercontent.com/assets/3220162/12590168/62da06f0-c416-11e5-8fdf-a5f37810f319.gif)

**Comment by jameskoster** [comment]
This should be fixed in the latest release; https://github.com/woothemes/storefront/issues/305
