### ISSUE TITLE
Allow menu button label on mobile to be modified via Customizer

### ISSUE THREAD

**Issue by jameskoster** [woothemes/storefront#313]
I see this question come up over and over again on the w.org forums. Do we think it'd be worth just making this an option in core?

@tiagonoronha @stuartduff

**Comment by stuartduff** [comment]
I think it's a valid request and if a change makes it easier for the customer then it's definitely something to consider. The customer could use a filter or similar but a setting for those with little to no knowledge of code would make it easier.

**Comment by tiagonoronha** [comment]
What if, instead of an option, we simply use the name of the menu assigned to that location? Or you guys think that's too confusing?

**Comment by jameskoster** [comment]
@tiagonoronha I thought about that but it doesn't feel very intuitive. I mean, most people are going to call this menu 'mobile' or something like that. I think it would be too confusing.

**Comment by stuartduff** [comment]
@jameskoster @tiagonoronha What about we document the filter **storefront_menu_toggle_text** to begin with and we can then easily link them to that showing some example code they can use.

Usually people can copy and paste code even if they don't understand it or can't write it.

**Comment by tiagonoronha** [comment]
Yeah... that makes more sense. 

The option wouldn't be that intuitive either. As you'd have to resize the window to actually see the text changing.

**Comment by jameskoster** [comment]
That's a good point @tiagonoronha.

@stuartduff we have a doc already :) https://docs.woothemes.com/document/change-the-primary-navigation-button-text/

But this (and the logo option) just seem to come up over and over again. I guess we'll leave it for now.
