### ISSUE TITLE
CSS expanded

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/storefront#314]
Why the CSS is expended and not completely minified? Any particular reason?

https://github.com/woothemes/storefront/blob/master/Gruntfile.js#L112

**Comment by sdbritton** [comment]
It's certainly easier to edit and troubleshoot when it is minified. I think
it should be left up to each site developer if they want to minify the CSS
or not.
On Feb 5, 2016 11:09 AM, "Nicola Mustone" <notifications@github.com> wrote:
>
> Why the CSS is expended and not completely minified? Any particular
reason?

**Comment by jameskoster** [comment]
No reason, it should be minified I think.

**Comment by claudiosmweb** [comment]
The ´expand: true´ is for the file system... See: http://gruntjs.com/configuring-tasks#files

> `expand` Process a dynamic src-dest file mapping, see "[Building the files object dynamically](http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically)" for more information.

In other words... Not related with "minified" files :P

**Comment by SiR-DanieL** [comment]
You're right @claudiosmweb but still there's a command to add in `cssmin` to "uglify" completely the CSS. I know there's one, can't find it though :)

**Comment by jameskoster** [comment]
OK, I remember why this is the case now. `grunt-contrib-cssmin` strips the comment which is required for WP to recognise the theme. Supposedly you can mark a comment as important so it doesn't get stripped, but that doesn't work for me. Needs further investigation.

The other stylesheets can be minified though.

**Comment by SiR-DanieL** [comment]
@sdbritton 

> reason?

We can save some KBs minifying the file. If there was a reason for having it expanded I'm ok with that, butsince there's no reason, I don't see why we shouldn't save those KBs :)

**Comment by claudiosmweb** [comment]
@jameskoster you can start comments with `/*!` so will not be removed...
