### ISSUE TITLE
Position of Breadcrumbs when WooCommerce Message is triggered

### ISSUE THREAD

**Issue by BusinessBloomer** [woothemes/storefront#322]
Hi guys, I may have found a bug @ storefront.

When an item is added to cart with Cart Redirect enabled, or when removing an Item from the Cart, the usual WooCommerce message appears on top e.g. "_____ has been added to your cart."

The problem is that this pushes down the WC Breadcrumbs, as opposed as showing under. I attach an image to show what I mean.

Let me know

~R

![storefront bug](https://cloud.githubusercontent.com/assets/16014385/13111517/17482b76-d57e-11e5-9bef-1d8eac9ba415.png)

**Comment by BurlesonBrad** [comment]
@BusinessBloomer would you consider that to be a bug? ....or more of a 'feature' / 'enhancement'?

**Comment by BusinessBloomer** [comment]
@BurlesonBrad not sure! Either way it needs to be fixed in my opinion :)

**Comment by jameskoster** [comment]
This is fixed in 2.0 https://cloudup.com/ck83DgpMaHp

**Comment by BusinessBloomer** [comment]
Thank you @jameskoster

**Comment by jameskoster** [comment]
No problem!
