### ISSUE TITLE
Add 'best selling' products to the homepage template

### ISSUE THREAD

**Issue by jameskoster** [woothemes/storefront#324]
What do you think @tiagonoronha ?

**Comment by tiagonoronha** [comment]
@jameskoster sure! It's just the output of another shortcode, so... :+1:

**Comment by jameskoster** [comment]
OK, where shall we put it in the homepage order?

We currently have;

`<?php
			/**
			 * @hooked storefront_homepage_content - 10
			 * @hooked storefront_product_categories - 20
			 * @hooked storefront_recent_products - 30
			 * @hooked storefront_featured_products - 40
			 * @hooked storefront_popular_products - 50
			 * @hooked storefront_on_sale_products - 60
			 */
			do_action( 'homepage' ); ?>`

After featured?

**Comment by BurlesonBrad** [comment]
Business minded, psychology minded, sharp thinking store owners would want to put their Best Sellers as high up on the page as possible.

Instincts would weight Best Sellers above product_categories. Definitely more important than recent_products.   But.... 

The question that might add a bit of value here is, _"Does the - 10,20,30 Default priority really matter?"_

Why do I mention that question? Well, after all, the End User can simply drag their elements around in the customizer themselves based on what their '**own**' priority is, right? 

Default, though?  Meh.... give it a 70 and let the store owner figure it out :wink:

**Comment by tiagonoronha** [comment]
@jameskoster add it to the bottom, I guess. If we add it to the top, I'm afraid there will be people upgrading without noticing that this new section got added and it might mess with their layout.

What do you think?

**Comment by jameskoster** [comment]
OK, the bottom it is.

**Comment by BurlesonBrad** [comment]
I got this one :+1: 


_...I think_
_...bear with me_

**Comment by BurlesonBrad** [comment]
@tiagonoronha @jameskoster I thought I'd give myself a challenge and contribute where I could.  I still can't figure out why two of those pull requests look like they do, and the one for storefront-template-functions.php looks a bit different. Oh well. I'll **_always be learning_** something I guess :wink: 

Anyhow, point being ~ **IT WORKS!**  Even if you fellas can java your grunt while the vagrant gulps broccoli with a composer  :open_mouth: ....er whatever..... 

 ...I'm kinda proud of it.

![storefront-best-selling-products](https://cloud.githubusercontent.com/assets/6208757/13731216/c01b7070-e931-11e5-8f25-7313e5290c2f.png)

**Comment by BurlesonBrad** [comment]
ok, that's better.  Should be good-to-go now.

**Comment by jameskoster** [comment]
Cheers @BurlesonBrad ! Your `@since` flag in the docblock is incorrect but I'll let you off xD
