### ISSUE TITLE
Load FontAwesome via CDN

### ISSUE THREAD

**Issue by jameskoster** [woothemes/storefront#331]
https://fortawesome.github.io/Font-Awesome/get-started/

**Comment by BurlesonBrad** [comment]
please don't.  
Simply loading one, two, six, or even a dozen icons is better than:

1.  creating a dependency on an external source
2.  adding http roudtrips to the speed

How many _total_ icons are actually really needed for Storefront?

**Comment by jameskoster** [comment]
@BurlesonBrad performance impact should be negligible. It's not actually possible to just load, one, two, six, or even a dozen icons. It's all or nothing.

I've seen a number of people asking to use the FontAwesome classes to add icons in their post content and/or customisations, this would solve that as well.

Back to the performance thing, it's one more http request and a little extra css. FontAwesome is pretty widespread so there's a good chance that your browser will have already cached the CSS, so performance would actually _improve_ in some cases.

Finally the benefit of doing this is that folks will always have access to the latest version of the lib.

**Comment by BurlesonBrad** [comment]
> not actually possible to just load, one, two, six, or even a dozen..... It's all or nothing.

Right.  At least I knew that part :stuck_out_tongue_winking_eye:   
What I've never understood though is why themes and plugins will load....
> #### **all**

 ...when the theme actually use a whopping 3 icons. Or some social plugin only used 8 social icons.  Or a plugin that used the phone class="fa fa-phone" and the map class="fa fa-map-marker".
If the theme uses 'em **all**, rock on ~ Let's load 'em up! _but......_

I know I'm not the rocket ninja genius coder @jameskoster, and sometimes it seems that a suggestion seems to carry more ***weight*** if I can [Grunt](https://github.com/ericmann/grunt-wp-underscores) a [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV/) on a command line while [Gulping](https://github.com/gulpjs/gulp) a [Twig](https://github.com/twigphp/Twig). But I would like some honest feedback from others on this before it's done, implemented, and Font Awesome is included and shipped with every Storefront installation by default.

_Is there a Page Builder?_ **Nope.** _Shortcodes included in the theme?_ **No.** _Sliders?_ **No way.**  Is it **"[Lean and Mean](https://www.woothemes.com/storefront/)"** ? **YES!**
> The Storefront philosophy is to do one thing well. In this case that is to provide a rock solid foundation for your next WooCommerce project.

Something in the lower left of this image below does not seem to belong.  **Can you spot it?**
![fa_sf_git](https://cloud.githubusercontent.com/assets/6208757/13289602/1f282410-dad6-11e5-9f30-32a442c08321.png)

_something in my gut is makin' me want to dig my heals in a bit on this one.  If I'm wrong, guess what ~ it ain't gonna hurt my feelings. Let me know! :+1:

**Comment by jameskoster** [comment]
We actually use quite a few icons but yeah, it's nowhere near _all_. 

Did you know that Storefront is already including FontAwesome? It's actually bundled in the theme. That might be where the confusion around this comes from.

Since we're _already_ loading the font, this would be a _better_ way to do it.
