### ISSUE TITLE
error  Stylesheet is missing. 

### ISSUE THREAD

**Issue by hazephase** [woothemes/storefront#332]
I get Stylesheet is missing. error when I look at the backend of my wordpress site

**Comment by BurlesonBrad** [comment]
If you've downloaded it from Github, that will happen.  The github repo doesn't include a style.css. It only includes a style.**S**css. 
![only-scss-in-storefront-on-github](https://cloud.githubusercontent.com/assets/6208757/13321533/18b81ae4-db95-11e5-8c20-313afc71fc46.png)
_CSS is the styling language that your browser understands and uses to style webpages. SCSS is a special type of file for SASS, a program written in Ruby that assembles CSS style sheets for a browser. SASS adds lots of additional functionality to CSS like variables, nesting and more which can make writing CSS easier and faster. SCSS files are processed by the server running a web app to output a traditional CSS that your browser can understand._

@hazephase  If you will downloaded Storefront directly from https://wordpress.org/themes/storefront/ then you won't have that issue :+1: 
![direct-download-storefront](https://cloud.githubusercontent.com/assets/6208757/13321440/9cc374f6-db94-11e5-90f3-309502fc73c2.png)

**Comment by jameskoster** [comment]
Just to expand on @BurlesonBrad's comment, if you do want to download Storefront from github for whatever reason, grab the zip file from the [releases](https://github.com/woothemes/storefront/releases) page. That will include the .css files.

**Comment by hazephase** [comment]
ok, thanks guys but I was hoping to get storeFront 2.0 on the release page its 1.6

**Comment by jameskoster** [comment]
2.0 is still in development :)
