### ISSUE TITLE
Improve UX with product reviews

### ISSUE THREAD

**Issue by kymcarlsson** [woothemes/storefront#333]
If a user gets submits a review and doesn't enter a comment like so:
<img width="678" alt="comment" src="https://cloud.githubusercontent.com/assets/10130454/13313630/a887eabe-db9f-11e5-945e-aebadb17da40.png">
They are presendted with this:
<img width="1079" alt="comment-result-novalidation" src="https://cloud.githubusercontent.com/assets/10130454/13313629/a88750c2-db9f-11e5-8d06-66ea8bf208cb.png">
I realise this is probably straight from WP/WC core:
https://github.com/woothemes/woocommerce/issues/3672 https://github.com/woothemes/woocommerce/issues/4083
Buuuut for storefront.. maybe some inline validation here for the text box and star rating would be a cool feature?

**Comment by jameskoster** [comment]
I like this idea but I'm not really sure where the feature belongs. As something that would be of benefit to all WooCommerce users I'd be hesitant to add it to Storefront. It's quite a niche thing as well so I'm not sure adding it to WooCommerce core is warranted. If anything this should probably be it's own small plugin. In fact, I wouldn't be surprised if one already exists.

Oh, look: https://wordpress.org/plugins/instant-comment-validation/ :-) Not sure if it works with WooCommerce, but reviews use the core commenting system so it should do.
