### ISSUE TITLE
css minification function

### ISSUE THREAD

**Issue by jameskoster** [woothemes/storefront#337]
When you have a bunch of Storefront extensions / child themes active the inline CSS can be quite cumbersome. Would be nice to at least minify it.

**Comment by jameskoster** [comment]
After some thought about this, the impact of minifying CSS on the fly with every page load would probably greater than that added by a few line-break characters. Not worth doing.

**Comment by tiagonoronha** [comment]
@jameskoster just to add that this could potentially be done with transients, the minification process would happen only once.

**Comment by jameskoster** [comment]
@tiagonoronha yeah that's where my train of thought led me. See https://github.com/woothemes/storefront/issues/348
