### ISSUE TITLE
Hook to remove single post meta not working

### ISSUE THREAD

**Issue by likethegoddess** [woothemes/storefront#339]
Action to remove single post metadata, as stated in storefront template content-single.php and confirmed in support thread, https://wordpress.org/support/topic/remove-post-meta-from-single-blog-page?replies=5, not working as expected. 

Created child theme including only style.css with no styles and functions.php with only the following snippet: 

    add_action( 'init', 'ltg_remove_meta' );
    function ltg_remove_meta() {
    	remove_action( 'storefront_single_post', 'storefront_post_meta', 20 );
    }

Single post meta remains. 

Two test sites (different hosting companies) reproduce the issue, including fresh WP install at http://likethegoddess.info.

**Comment by jameskoster** [comment]
Ah, I see the issue. Looking at code is so much nicer of github xD Will respond on .org.
