### ISSUE TITLE
Outline quirks in FF

### ISSUE THREAD

**Issue by RiaanKnoetze** [woothemes/storefront#346]
Ticket: 395626-woothemes-zd

When the ```:focus``` pseudo state is triggered on product listings, there are additional lines showing up at the top of the image and between the title and price when using FireFox 44 (Both on Mac and Win 10).

Screenshot:

![image](https://cloud.githubusercontent.com/assets/13743465/13770350/0de0317a-ea8f-11e5-9b83-00616d5e77ec.png)

I was able to replicate this on local.

The temporary fix I suggested to the customer was as follows:

```
ul.products li.product a:focus {
  display: block;
}
```

**Comment by jameskoster** [comment]
This is a tricky one. Adding that code will make all anchors in the product display block, including the buttons. Instead, let's add a unique class to the main product anchor in WooCommerce core and use that.
