### ISSUE TITLE
Customize setting and inline style storage/performance

### ISSUE THREAD

**Issue by jameskoster** [woothemes/storefront#348]
We currently run ~15 instances of `get_theme_mod()` on every page load in Storefront core. I'd like to investigate improving that. 

Here's an idea; assign and store all of the individual theme_mods and associated css to a single theme_mod or transient on appropriate occasions.

So, on:

* `customize_save_after`
* `after_theme_switch`

Get all the separate theme_mods, prepare the css and assign them to a single theme_mod, e.g. `storefront_styles`.

Then in `add_customizer_css()` call `wp_add_inline_style()` as we do now, but reference the single `storefront_styles` theme_mod.

We'd need to ensure that the 'un-stored' version is loaded whilst the Customizer is open so that the preview works correctly.

I don't suppose this would have a huge impact, but every little helps. If we could make it extensible so that child themes/extensions could hook in then the impact would be more significant.

Thoughts @tiagonoronha @mendezcode? Does this make sense? Is it worth it?

**Comment by mendezcode** [comment]
@jameskoster I think the single theme_mod approach should work well in this case. We do indeed have a lot of calls to `get_theme_mod()', so simplifying those would be good for performance.

The impact may be minimal performance-wise in Storefront itself. When used with child themes, then the approach makes even more sense and the impact should be more considerable indeed.

I think this is a great idea, totally worth it! :thumbsup:

**Comment by jameskoster** [comment]
Please have a look @tiagonoronha @mendezcode. Let me know if you've any feedback :)

**Comment by tiagonoronha** [comment]
@jameskoster this is a start, nice idea!

I'd add a transient to get_storefront_theme_mods() so you only make those calls once and then the result is cached.

Then clear the transient when the Customizer is saved.

**Comment by mendezcode** [comment]
Hey @jameskoster, I did refactor the method a bit in 767a1467feaae93a9065005040b07eeb4888a445, to make sure the array is (statically) cached in the function. This means future calls to the method will use the cached version.

A transient would also work in this case. Interestingly I didn't think of a transient, now that I see Tiago's comment (after I committed). Either should work fine ;-)

**Comment by tiagonoronha** [comment]
@mendezcode but ins't that array going to be rebuilt on each page load? That's why I think a transient would be better in this specific case.

**Comment by mendezcode** [comment]
@tiagonoronha Yes, that's correct. In this case it makes absolute sense to implement as a transient instead. Very good point! :+1:

**Comment by tiagonoronha** [comment]
Actually, upon further review, a transient is not needed.

I noticed that the inline CSS is being cached in `set_storefront_style_theme_mods()` so the function is actually only being while that CSS is being generated.

Looks good guys :)

**Comment by jameskoster** [comment]
I'll merge. If either of you want to make any further tweaks please feel free :)
