### ISSUE TITLE
Checkout Add-ons breaks checkout layout

### ISSUE THREAD

**Issue by mikeyarce** [woothemes/storefront#352]
Tested in both current release and latest master.
![screen shot 2016-03-17 at 11 31 26 am](https://cloud.githubusercontent.com/assets/3220162/13856732/cf4884fc-ec33-11e5-8327-9eb8321c53a3.png)

I think because it's a 2 column layout and the Checkout Add-Ons live outside of the first column, `col2-set` it treats it like the first column so the order details get properly moved to the left of that area instead of the top.

**Comment by jameskoster** [comment]
Hmmm, I'm seeing this: https://cloudup.com/ceo_yZ6g5JY

Storefront latest master,
Checkout add ons latest master.

Looks ugly but not broken. I'll fix that but want to replicate exactly what you have. What add-ons have you configured? Where have you specified they be displayed?

Cheers!

**Comment by jameskoster** [comment]
@mikeyarce *poke* :)

**Comment by mikeyarce** [comment]
Here are my Checkout Add-On settings:
![screen shot 2016-03-20 at 5 55 59 pm](https://cloud.githubusercontent.com/assets/3220162/13908686/3c67efda-eec5-11e5-9abd-debf4b0706d9.png)
Here is my checkout page:
![checkout-add-ons-bug](https://cloud.githubusercontent.com/assets/3220162/13908689/42942680-eec5-11e5-9eed-16fb96eec7ce.gif)

Running the latest master of both.

**Comment by jameskoster** [comment]
I'm unable to replicate that behaviour :( Any other plugins/extensions active that might influence this?

@tiagonoronha would you mind taking a look at this when you have a moment?

**Comment by BurlesonBrad** [comment]
@mikeyarce the rough thing about 'diagnosing' SF bugs is that in order to get it narrowed down, one would have to know **everything** about the environment: 
1. Is the [Storefront Checkout Customiser](https://www.woothemes.com/products/storefront-checkout-customiser/) plugin being used? If so, do you have it toggled for "distraction free checkout"?  _I ask b/c the order details (the right side) looks rather narrow_
2.Besides [Checkout Add Ons](https://www.woothemes.com/products/woocommerce-checkout-add-ons/), what **other** SF extensions are in your setup?

If @jameskoster nor I can replicate your site's behavior, then that doesn't imply that the bug isn't present. It totally **can be** there. _(and it'd be nice to narrow down quickly)_ But if the similar behavior can't be replicated, it simply means that you haven't given enough **information** needed to **replicate** the exact similar environment :+1: 

Does that make sense?

**Comment by mikeyarce** [comment]
Here are my steps :)

1. Brand new WordPress install
2. Install WooCommerce + WooCommerce Checkout Addons
3. Install Storefront 1.6.1 (issue happens on latest master as well, but for the sake of this test I'll stick with 1.6.1)
4. Add one item to the checkout add-ons:
![screen shot 2016-03-20 at 5 55 59 pm](https://cloud.githubusercontent.com/assets/3220162/13908686/3c67efda-eec5-11e5-9abd-debf4b0706d9.png)
5. No other plugins installed, no custom CSS, nothing else.
6. I'm on a Mac, using a Thunderbolt display, on Chrome, also happens in Firefox.

@jameskoster I noticed your screenshot doesn't include the "Addiontional Information" section that I see on my default install:
![screen shot 2016-03-21 at 11 16 03 am](https://cloud.githubusercontent.com/assets/3220162/13929222/52ebcf2e-ef56-11e5-8088-0a0e413631ab.png)
Could that be part of the issue?

**Comment by jameskoster** [comment]
@mikeyarce that box appears in the billing address form. I see it on my install.

What have you set here: https://cloudup.com/ck35Z_RU54R ?

**Comment by BurlesonBrad** [comment]
@jameskoster wouldn't his screenshot dictate that he would have it set to 'after'?
"Before Billing Details" puts it over in the second ```div```
"Before Order Summary" puts it in the second ```div``` as well.
**"After Billing Details"** is the only one that will _(should)_ put it in the first ```div```.

> your screenshot doesn't include the "Addiontional Information" section

@mikeyarce, @jameskoster 's screenshot was from 
``` /wp-admin/admin.php?page=wc-settings&tab=checkout ``` not the checkout page. :wink: 
If you'll got to WooCommerce>Settings>Checkout Tab, _(or you can add that specific url to your local site,)_ then scroll down a bit, you'll be able to see _where_ the box is to answer Jame's question.

- [ ] -  You've set the checkout page, right? 
![set-checkout-page](https://cloud.githubusercontent.com/assets/6208757/13936912/1838e266-ef8f-11e5-9dd3-58725e81eb35.png)

- [ ] -  See how narrow your order review area is? As trivial as it might sound to ask, what'd you set as the page template? It would _appear_ to be ```default```, but I want to get a confirmation from you first.

- [ ] - I've thrown every plugin I could find from my own to client's to anything else _Woo_ at this scenario, and I simply can't replicate it. Any chance you'd be willing to post a gist of the **System Report** 

- [ ] - Are there any Chrome Extensions running? _specifically we're looking for anything that might jack with the current browsing scenario

- [ ] - Can you open the 'Inspect Element'?  Pull up the error section if possible and take a screenshot of that section.
![error_message](https://cloud.githubusercontent.com/assets/6208757/13937336/1959a6dc-ef92-11e5-872c-f13679cb43c9.png)

**Comment by BurlesonBrad** [comment]
oh, hey @mikeyarce : Thanks for the ```init``` tip :+1:  over in the forums. Totally forgot that part :open_mouth:

**Comment by mikeyarce** [comment]
@jameskoster I have the default settings "Before Order Summary":
![screen shot 2016-03-23 at 9 30 02 am](https://cloud.githubusercontent.com/assets/3220162/13992582/e408012e-f0d9-11e5-9d08-25fd151113ee.png)

If I set it to "After Billing Details" the issue goes away.

@BurlesonBrad lol - I meant the screenshot from the earlier comment he made, not the settings one ;)  I think the issue has to do with the settings as James mentioned, but I appreciate your suggestions!

**Comment by jameskoster** [comment]
That should do it. Doesn't look great when you display the add-ons above the billing details, but it works.
