### ISSUE TITLE
Add oEmbed styles

### ISSUE THREAD

**Issue by mikeyarce** [woothemes/storefront#353]
I don't think we currently have any oEmbed styles:
![screen shot 2016-03-17 at 1 27 05 pm](https://cloud.githubusercontent.com/assets/3220162/13882647/a317548e-ece3-11e5-8405-cb1eb3e6a560.png)
Would be neat to add some to make them look more Storefront-like.
Details on how to do it: https://make.wordpress.org/core/2015/10/28/new-embeds-feature-in-wordpress-4-4/

**Comment by jameskoster** [comment]
Good idea, although I'm not sure how much we can add xD

I'll have a play.

**Comment by jameskoster** [comment]
Done! 

Before: https://cloudup.com/iyftW8876G4
After: https://cloudup.com/iUX4SQ4tTgZ

**Comment by SiR-DanieL** [comment]
@jameskoster wouldn't be better to make the Buy now button purple?

**Comment by jameskoster** [comment]
Good idea @SiR-DanieL :)
