### ISSUE TITLE
WooCommerce Customiser doesn't show up on Product Pages

### ISSUE THREAD

**Issue by mikeyarce** [woothemes/storefront#355]
In the latest Master of Storefront, I noticed the Storefront WooCommerce Customiser is not showing up.  Switching to the latest Storefront from the .org repo brings it back:
![screen shot 2016-03-20 at 5 52 47 pm](https://cloud.githubusercontent.com/assets/3220162/13908646/96faa68c-eec4-11e5-9fa5-332ca82fefbc.png)
This is after running grunt after pulling the repo down.

**Comment by jameskoster** [comment]
Seems to be working fine here: https://cloudup.com/c40gKYLV87b Are you able to do some further digging? ^^

**Comment by mikeyarce** [comment]
I tried on a new install with Storefront latest master, and these plugins:
![screen shot 2016-03-21 at 11 03 46](https://cloud.githubusercontent.com/assets/3220162/13928846/a138c3fa-ef54-11e5-8cbc-1e358efeefaf.png)
It won't show up in the product page and actually not even in the Customiser.

**Comment by jameskoster** [comment]
Still unable to replicate this one :( @tiagonoronha would you mind taking a look to confirm?

**Comment by jameskoster** [comment]
*ping* @tiagonoronha xD

**Comment by tiagonoronha** [comment]
@jameskoster @mikeyarce 

Oops!

Can't replicate this one either. Updated the plugin to 1.8.2 and also the latest from master, all seems good. :/

**Comment by jameskoster** [comment]
I'm going to close this. If you have any further clues as to what might cause this please reopen @mikeyarce 

Was this reported by a customer? Or just something you noticed?
