### ISSUE TITLE
Beta-1: Logo squished in mobile view

### ISSUE THREAD

**Issue by mikeyarce** [woothemes/storefront#359]
If you have a long height logo, it gets really squished in the mobile view:
![sf2-logo](https://cloud.githubusercontent.com/assets/3220162/14023557/181749d4-f1a2-11e5-9848-a530c9aab907.gif)

Maybe we can switch to a text title in mobile, or account for taller logos somehow?

**Comment by jameskoster** [comment]
Looks like a borked max-height. Will check.
