### ISSUE TITLE
Customizer Selective Refresh

### ISSUE THREAD

**Issue by jameskoster** [woothemes/storefront#362]
Let's implement this wp 4.5 feature for 2.1.

Implementation guide here; https://make.wordpress.org/core/2016/03/22/implementing-selective-refresh-support-for-widgets/

We can use Selective Refresh to handle widgets/sidebars, plus all of the settings that currently rely on javascript for asynchronous previews.

- [ ] Selective refresh for widgets
- [x] Selective refresh for site title / tagline
- [x] Remove old javascript

**Comment by BurlesonBrad** [comment]
**Yo Kostinator!** If I try to take on this challenge _#AlwaysBeLearning_  then, I have to do **two** edits, right?  _Why?_ Well, b/c the way I see it: **Why wait for 2.1?** :facepunch: 

I have to edit the **current** version.  _But, I'm still not done though right?_
How do I fork that one up yonder with the 2.1 tag?  Mine ain't got that option!
![sf-git-no-tag](https://cloud.githubusercontent.com/assets/6208757/14938629/4c4854e0-0eef-11e6-9b35-dbdab6913243.png)

**Comment by jameskoster** [comment]
Played around with this tonight, unfortunately I don't think the api is quite at a stage where I can be as adventurous as I'd originally planned. 

For now, we'll remove the javascript which is kinda clunky anyway and apply selective refresh to appropriate places.
