### ISSUE TITLE
2.0 Beta-1: Calculate shipping is choppy

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/storefront#364]
When calculating shipping from the cart, it makes the table data width larger, and appears choppy: http://cld.wthms.co/1cUhE/5EM7VihT. The selects over extend as well.

**Comment by jameskoster** [comment]
Which browser? Doesn't seem to be doing that for me.

**Comment by WPprodigy** [comment]
Chrome for me ¯\\\_(ツ)\_/¯

**Comment by jameskoster** [comment]
Cannot replicate.
