### ISSUE TITLE
menu width

### ISSUE THREAD

**Issue by BurlesonBrad** [woothemes/storefront#372]
I had noticed this bug a few months ago, but, instead of reporting it, they just changed their layout.  That's coming back around to bite me in the rump and make me regret not writing this up back then.

Storefront Blog Customiser
Storefront Designer
Storefront WooCommerce Customiser
**all current of course**
Header Layout = Central
Sticky Header (no cart & no search)
General Layout = Right
Site Width = True
Content Frame = False

![fbc-menu](https://cloud.githubusercontent.com/assets/6208757/14479023/49c45722-00e0-11e6-86be-9d7237ef1e9d.png)

The menu extends fine on the left. For some reason though, the width is set at 95% rendering no love  at all to the right side of the menu area and leaving it incredibly empty and alone :broken_heart: 

![no-love](https://cloud.githubusercontent.com/assets/6208757/14479265/5f5315d6-00e2-11e6-8424-0d93c57216a0.gif)
If 'ya gotta love :heart: it simply must be **100%** _(...width as well!)_

**Comment by jameskoster** [comment]
This is an issue in the designer extension. Will fix it there :)
