### ISSUE TITLE
parent theme, child theme, or theme customization plugin ??

### ISSUE THREAD

**Issue by pixeline** [woothemes/storefront#374]
Hi!
I've been advised to use Storefront for an upcoming project using woocommerce. I really like what I'm seeing in the upcoming 2.0.0 beta. Now, I first thought I'd use Storefront as a starting base.  Then I thought, ok, let's follow their advise and build a child theme so I can get all the bounties from 2.0 when it is release-ready. 
So I find your storechild starter child theme, awesome... Which [advises to actually use a plugin to customize the theme](https://github.com/woothemes/theme-customisations) because so you know... I can get the storechild updates I guess.
I'm confused.

Our project will be build around woocommerce but will be functionally more than a shop, with a strong narrative layer. Also, it is a client project and will not be released on any theme store. It will be tailormade to the customer needs. For example, all the theme customization functionality via the backend UI is not necessary (on the contrary, I 'll need to remove that entirely).

With that in mind, what would you advise I do: 

 1.  not use SF at all (but mimick its organisation),
 2.  use SF as a parent theme, 
 3.  use SF as a child theme,
 4.  use SF as a child theme + the customization plugin

I'll continue my own research but I'm interested in your advise and points of view.

Thank you very much,
Alex.

**Comment by tiagonoronha** [comment]
Hi @pixeline.

Use Storefront + Storechild.

We use Storechild as starter for our own child themes. Ignore the message you see in functions.php, that only applies if you are buying a child theme from us and you want to do customizations to it.

Hope this helps. :)

**Comment by pixeline** [comment]
Got it, awesome. Thank you for the speedy reply!

**Comment by zwiesman31** [comment]
@gigitux Storefront's functions.php still references the following: 

/**
 * Note: Do not add any custom code here. Please use a custom plugin so that your customizations aren't lost during updates.
 * https://github.com/woocommerce/theme-customisations
 */
 
 That seems to throw fatals at times. Can that option be reviewed and the info updated? Thanks!
