### ISSUE TITLE
WooCommerce oEmbed

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/storefront#375]
Seems that it is broken.

![](http://cld.wthms.co/1iqcT/49rD8sda+)

I noticed it today after the update to the beta 2

cc @jameskoster

**Comment by jameskoster** [comment]
Hm, that might be a woothemes.com issue. It looks pretty funky in Twenty Fifteen as well; https://cloudup.com/cRUgTvGUpy3

**Comment by SiR-DanieL** [comment]
cc @kloon @bryceadams

**Comment by jameskoster** [comment]
Don't think this is a Storefront issue so I'm gonna close for now.
