### ISSUE TITLE
npm installation error, maybe path error in npm file

### ISSUE THREAD

**Issue by hrharish111** [woothemes/storefront#376]
s/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/harishhr/wootest/storefront/node_modules/node-sass/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Linux 3.13.0-32-generic
gyp ERR! command "/home/harishhr/.nvm/v0.11.13/bin/node" "/home/harishhr/wootest/storefront/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/harishhr/wootest/storefront/node_modules/node-sass
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
Build failed
npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/home/harishhr/.nvm/v0.11.13/bin/node" "/home/harishhr/.nvm/v0.11.13/bin/npm" "install"
npm ERR! cwd /home/harishhr/wootest/storefront
npm ERR! node -v v0.11.13
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/harishhr/wootest/storefront/npm-debug.log
npm ERR! not ok code 0

**Comment by jameskoster** [comment]
I just ran a test and had no problems. I see you're using GYP, could it be related to that? Try just doing an `npm install`?

Going to close this as I'm 99% sure it's not an issue in Storefront codebase.
