### ISSUE TITLE
Hotlinking of resources and WordPress TRT Requirements

### ISSUE THREAD

**Issue by WPDevHQ** [woothemes/storefront#377]
Hotlinking to external resources as in [FontAwesome CDN](https://github.com/woothemes/storefront/blob/master/inc/class-storefront.php#L195) would break the TRT requirements namely that all themes must be self contained.

Other than Google fonts all resources must be bundled with the theme.

**Comment by BurlesonBrad** [comment]
........so,  Why has this just come up?

**Comment by WPDevHQ** [comment]
It has been the case for a long time - must have been missed in the review. If that's waht you are asking.

**Comment by jameskoster** [comment]
Dang, that's a shame.

@WPDevHQ do you have a link to that specific requirement?

**Comment by WPDevHQ** [comment]
Sure @jameskoster 
Here's the relevant link: [Required: Stylesheets And Scripts](https://make.wordpress.org/themes/handbook/review/required/#stylesheets-and-scripts) - 4th point.
