### ISSUE TITLE
[2.0 beta 2] Responsive issues

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/storefront#378]
This is how my header looks like on Desktop:

![](http://cld.wthms.co/1cxDR/3cwrbpT6+)

This is how it looks like on mobile:

![](http://cld.wthms.co/182GP/5IO8atpt+)

This is how it looks like with Hamburger Menu active:

![](http://cld.wthms.co/1bY0p/1PzX1O1S+)

cc @tiagonoronha

**Comment by jameskoster** [comment]
Which extensions do you have active besides the hamburger menu? It's looking fine here; https://cloudup.com/cbtvfztIHCI

**Comment by SiR-DanieL** [comment]
* Snapshots
* Storefront Beta Tester
* Designer
* Blog Customiser
* [Top Bar](https://wordpress.org/plugins/storefront-top-bar/)

**Comment by jameskoster** [comment]
Might be an issue with one of the header layouts in designer. Try deactivating that quickly and let me know? :)

**Comment by SiR-DanieL** [comment]
nope, still same issue without Storefront Designer

**Comment by emzo** [comment]
I think the lack of margin at the bottom of the header on mobile is because it looks like you've removed (unhooked) the `storefront_header_cart` from the `storefront_header`. I had the same issue and had to change some CSS to put some margin back in.

**Comment by SiR-DanieL** [comment]
Nope, I don't have such custom code. I also tested without Storefront Top Bar and the issue persists.

**Comment by emzo** [comment]
Ok, maybe you haven't removed it manually, but the header cart is definitely not there from your screenshots. What I'm saying is that the lack of the cart in the header is what's causing the margin issue. Looks identical to my header when I manually unhooked the cart from the header.

Did you disable the header cart using Storefront Designer?

**Comment by SiR-DanieL** [comment]
Ah no wait, sorry. I don't have WooCommerce installed, so the cart is not there.

**Comment by jameskoster** [comment]
No WooCommerce was the issue. Should be fixed now!
