### ISSUE TITLE
Updating from v1.6.1 to v2.0.0 RC 1

### ISSUE THREAD

**Issue by seb86** [woothemes/storefront#380]
@jameskoster After updating the theme using the Storefront Beta Tester, I came across this first issue. I made sure that my browser cache was cleaned but still got the same results. No settings have changed either.

The Header is Broken for the Site Title and Menu Links. See screenshot below.

![Site Title and Menu Links are incorrect](https://cldup.com/8vxeYGjtj6.png)

Let me know if you get the same results.

**Comment by jameskoster** [comment]
Nope, not seeing that. Must be your customizer settings? Have a look in the inspector to see where that color is coming from.

**Comment by seb86** [comment]
@jameskoster The settings were left as default in the customizer. I'm not using a child theme either. This was a clean install of Storefront 1.6.1 and then upgraded to v2.0.0 RC 1.

Here is a screenshot highlighting where the CSS is affecting the site title.

![Site title CSS issue](https://cldup.com/UqmdIK4D-5.png)

However when viewing the site while using the Customizer, the site title and menu links appear and standard links change to purple.

![Theme Customizer](https://cldup.com/vgj_se2Jbj.png)

**Comment by seb86** [comment]
@jameskoster I just changed the header background colour and then reverted it back to default so that I can press the save button in the customizer. Now when viewing the site it appears as it should.

So it looks like the upgrade of the theme does not apply the default settings which is added inline.

![Inspector 2](https://cldup.com/bun3BfD56R.png)

**Comment by jameskoster** [comment]
I just tested this on a fresh install. 

* Installed Storefront 1.6.1
* Reset the Customizer using Customizer Reset
* Upload 2.0.0

All worked perfectly. Any more insight you can provide? @tiagonoronha perhaps you can test this?

**Comment by tiagonoronha** [comment]
@jameskoster tested and all seems to be working fine. I also tried a couple variations, like not reseting the Customizer, also ok.

**Comment by seb86** [comment]
So it was just a random event for me. How odd.

@jameskoster If you did a fresh install why did you need to do a reset on the customizer?

**Comment by jameskoster** [comment]
Sorry, wasn't a fresh install. Was on a site where I'd previous had Storefront installed. I was just making 100% certain the Customizer was clean. Also tested without the reset and didn't have any issues.

I'll close this, but if you can pinpoint exactly what caused the issue please reopen :)

**Comment by seb86** [comment]
@jameskoster I can't say for sure but maybe the issue was due to a possible WordPress update which cleaned the customizer settings.
