### ISSUE TITLE
Font Awesome stylesheet is missing in RC1

### ISSUE THREAD

**Issue by WPDevHQ** [woothemes/storefront#382]
The font-awesome stylesheet and the enqueue method are missing in RC1

**Comment by BurlesonBrad** [comment]
uhhhhhhhhhhhhhhhhhhhhhhhhh
ummmmmmmmmmmmmmmmm
ehhhhhhhhhhhhhhhhhhhhhhhhh

_how do I say this?............._  @WPDevHQ lemme just reference this:
# #377 

:laughing:

**Comment by WPDevHQ** [comment]
#377 Was about hotlinking!

The requirement is to bundle the stylesheets/scripts and enqueue them from with in the theme.

**Comment by WPDevHQ** [comment]
This: `wp_enqueue_style( 'fontawesome', get_template_directory_uri() . '/assets/css/font-awesome.min.css', 'storefront-style', $storefront_version );` is allowed but this:` wp_enqueue_style( 'fontawesome', '//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css', 'storefront-style', '4.5.0' );` is not!

**Comment by BurlesonBrad** [comment]
ahh.......... :+1:  _see, that's why I shouldn't be making themes :open_mouth: 

I wonder if I can actually make a correct fork & merge again.  Let's find out............ :hourglass_flowing_sand:

**Comment by BurlesonBrad** [comment]
Wait, didn't @jameskoster already do this?
https://github.com/woothemes/storefront/commit/408a70dfd5ea204aac82a27756d2045d0cf98052

**Comment by WPDevHQ** [comment]
408a70d only added the fonts but not the stylesheet - the cdn enqueue was removed but not replaced with the internal enqueue.

**Comment by jameskoster** [comment]
I decided to include the fonts, but not the css. We didn't include it before and it's easy to add via child theme if someone really needs it.

**Comment by WPDevHQ** [comment]
Doesn't that then leave Storefront with blank spots where it calles the `angle-down`, `angle-right` for menu item has child and `shopping-basket` for the menu cart? Just a few spots from the top of my head.

**Comment by jameskoster** [comment]
We don't reference any of the FontAwesome classes in Storefront. We add the icons manually using a sass mixin.

Including the FontAwesome CSS is only useful if folks are adding icons to their content. Given the majority of folks don't do this, it's not worth loading another asset imo.

I added it via cdn originally as most folks would already have that cached in their browsers and the performance impact would have been negligible.

**Comment by WPDevHQ** [comment]
OK got you. Its just the icons did not show up on one of my local dev installs so figured I'd check in :)

**Comment by jameskoster** [comment]
Hmm, do you have an old version of FontAwesome installed locally @WPDevHQ ? Shouldn't be any missing icons..!
