### ISSUE TITLE
Bottom 1% account menu < this does not make sense

### ISSUE THREAD

**Issue by el-presidente** [woothemes/storefront#390]
We don't use the account functionality in WC/WP so the need of people logging in on the new bottom handheld menu's 1st choice is redundant. We just want customers to place an order without creating an account so having a menu item in the handheld menu is overkill. 

So I guess a future enhancement or plugin request would be to choose an icon and where it would lead to. I would use it to start up a Zopim chat for example. The new bottom menu has taken over its overlay so i've deleted zopim temporary.

**Comment by jameskoster** [comment]
Hey,

You can actually filter these links to replace / add your own. See here; https://github.com/woothemes/storefront/blob/master/inc/woocommerce/storefront-woocommerce-template-functions.php#L251

I'll be writing about this on the 2.0.0 release post which will be published on our [dev blog](https://storefront.wordpress.com/) very soon.

**Comment by jameskoster** [comment]
Docs link; https://docs.woothemes.com/document/customise-the-links-in-the-handheld-footer-bar/ :)
