### ISSUE TITLE
[2.6] Need to update the "My Account" page CSS

### ISSUE THREAD

**Issue by claudiosmweb** [woothemes/storefront#393]
The changes are not included on Storefront 2.0 and we announced it: https://storefront.wordpress.com/2016/03/23/storefront-2-0-0-beta-1/

**Comment by jameskoster** [comment]
They are? 

https://github.com/woothemes/storefront/blob/master/assets/sass/woocommerce/woocommerce.scss#L1263

**Comment by claudiosmweb** [comment]
Seems fixed now in 2.0.1. The files had in my installation lacked this class, but I'm seeing repository on WordPress and it seems all right... Maybe I did something wrong here xD, apologize for the false alarm.
