### ISSUE TITLE
Nice thought forcing dimensions of site header image and site icon but...

### ISSUE THREAD

**Issue by Lewiscowles1986** [woothemes/storefront#395]
When I attempt to use an SVG image as the site header image, or site icon I am forced to crop with no choice not to do so, and no capability of doing so... 

It's a lovely thought to help people, but to block people from knowingly supplying an image of different dimensions to those you advise (or dimensions WordPress is incapable of deducing) is an exercise in patience.

I would really appreciate this becoming a warning, or notice rather than a blocking feature.

**Comment by BurlesonBrad** [comment]
@Lewiscowles1986 I would like to simply point out that YOU and the average Storefront user might not be on the same ......._(how do I say....)_ level of understanding. :wink:

As @georgestephanis [mentioned](https://gist.github.com/Lewiscowles1986/44f059876ec205dd4d27#gistcomment-1433903), sanitize it, and fit it to your ...level of understanding. 

And, while you might see the security risks of svg's to be "the job of a good antivirus & malware suite", I can't see it being anything **but** a big huge gigantic blocking feature. :+1: by default.  Those who **can** get around the _block_ are probably the only one's who **should**. Those who can **not** should probably be deterred.

**Comment by jameskoster** [comment]
You can filter `storefront_custom_header_args` :)

**Comment by Lewiscowles1986** [comment]
thx, I'll add the hook to my SVG plugin so it automatically bypasses this "feature"
