### ISSUE TITLE
Display page heading before content

### ISSUE THREAD

**Issue by shivapoudel** [woothemes/storefront#396]
@jameskoster I would like to display Page Heading section using Storefront just like in WooThemes. Should we have to use metabox or widget to display specific page title and description along with sign up in every page. Is there any storefront widget or extensions built previously. Please advice!

I am talking about this page heading section in WooThemes:-
![capture](https://cloud.githubusercontent.com/assets/3774827/15306213/72c519b8-1be8-11e6-9eeb-6e5d98952db4.PNG)

**Comment by BurlesonBrad** [comment]
@shivapoudel   How's this?

![shivas-github2](https://cloud.githubusercontent.com/assets/6208757/15308452/2482a56c-1ba3-11e6-939a-c9e3f3412e17.png)


```
<div style="width: 50%; float: left; text-align: left; background-color: #ADD8E6; padding:10px 10px 10px 10px; ">
<h1>Sign Up</h1>
<strong>Register for Shiva's Hair Club</strong>
</div>
<div style="width: 50%; float: right; text-align: right; background-color: #ADD8E6; padding:10px 10px 12px 10px;"><a class="button" href="http://demo.woothemes.com/storefront/shop">Go shopping →</a>

<em>Get Access to Awesome Flowing Thick Hair</em></div>
```

There's also the option of jacking with the [Storefront Footer Bar](https://wordpress.org/plugins/storefront-footer-bar/screenshots/).  It's not the same thing, but it's got the same "guts" as what you are wanting.  Attach the footer bar contents for a ```page_id``` with a metafield and you could easily echo a specific footer bar anywhere in your page with completely unique content for page by page call-to-actions.

@wpexplorer does a GREAT job in his [Total Theme](http://wpexplorer-themes.com/total/docs/footer-callout/).  Perhaps we could make something similar for Storefront :+1:

**Comment by jameskoster** [comment]
There's no an option or plugin that I'm aware of @shivapoudel.

It's be an easy plugin to make though. Just unhook the current page title, re-hook it on the appropriate action and style accordingly :)

**Comment by shivapoudel** [comment]
@jameskoster @BurlesonBrad Thanks for the workaround idea xD

**Comment by wpexplorer** [comment]
@BurlesonBrad - Thanks for the mention!

You can also use the 'storefront_content_top' hook or 'storefront_before_content' hook that is in header.php of Storefront to easily add a new heading area like this ;)

ps: By the way Brad In our Total theme you can also move the Footer Callout section to under the header if you wish and even alter the text to display a heading if you wish ;)

**Comment by shivapoudel** [comment]
A few hours of hackathon to create a plugin and add CPT with control options in its meta box for what to display and where to display (product category, page, etc) could solve this situation. Thanks all of you for the great advice!

**Comment by jameskoster** [comment]
Did you build this @shivapoudel ? Planning to upload to .org?

**Comment by shivapoudel** [comment]
@jameskoster I have started within a plugin which I used to manage the overall store functionality. Hence not planning to upload to .org :)

**Comment by jameskoster** [comment]
I see, np :)
