### ISSUE TITLE
Structured data

### ISSUE THREAD

**Issue by opportus** [woothemes/storefront#399]
The structured data html markup on single and archive post page is completely messed up (according to Google Structured Data Tool).

Eg on single post page:
A lot of errors in Article and BlogPosting types.
Properties of Article and BlogPosting types conflicting each other. Why to keep both of them?
Itemtype attribute value for image is incorrect.
Missing required properties in both Article or BlogPosting: author, name, publisher, dateModified, mainEntityOfPage, etc…

I doubt that is a personal issue so you could check all this by yourself more accurately.

Even if it has not a big impact on the way Google will handle the structured data (but I believe that at that point it does), for the sake of "not being bumped by so many errors", would you consider fixing or even better removing all that structured data html markup and use a dynamically generated json file which would be way more flexible to work on for so many people using your great theme?
For example, something like this: https://github.com/opportus/storefront-sp/blob/master/modules/class-data-structurer.php

Thank you !

PS: I apologize if my bad english made it hard to read.

**Comment by jameskoster** [comment]
Hey,

Yup, I think we'd definitely consider that. Wanna send a PR? :)

**Comment by opportus** [comment]
Hi,

Sure, I'd love too ! :)
