### ISSUE TITLE
Jetpack Tiled Mosaics aren't full width

### ISSUE THREAD

**Issue by DustinHartzler** [woothemes/storefront#406]
With Storefront 2.0.2, the width of a tiled mosaic gallery is not the full width of the content column.

<img width="1128" alt="storefront" src="https://cloud.githubusercontent.com/assets/2293077/15746728/0461f0e8-28d8-11e6-9a25-4c3a1991ae4a.png">

This trickles down to child themes as well.

<img width="1223" alt="screen shot 2016-06-02 at 3 38 54 pm" src="https://cloud.githubusercontent.com/assets/2293077/15746778/31fa7eee-28d8-11e6-8b23-f8a574603f8f.png">

**Comment by DustinHartzler** [comment]
And here is TwentySixteen:
<img width="1255" alt="screen shot 2016-06-02 at 3 41 50 pm" src="https://cloud.githubusercontent.com/assets/2293077/15746892/a33fbd26-28d8-11e6-87b9-ea42130f4a8f.png">

**Comment by jameskoster** [comment]
Seems our `$content_width` declaration was being ignored. 

If necessary, until 2.0.3 is available folks can use this plugin to fix; https://wordpress.org/plugins/custom-content-width/
