### ISSUE TITLE
Credit Card Radio Buttons do not have "Select" mode

### ISSUE THREAD

**Issue by DanielSantoro** [woothemes/storefront#407]
Hey guys and gals,

I came across a quirk with Storefront 2.x, where if I'm using the Simplify Commerce by MasterCard option during checkout the radio buttons don't seem to do anything:

http://recordit.co/IkLa96qEke

Since the rest of that area uses radio buttons that select, could we make the FontAwesome icon switch if a field is selected _or_ change that appearance away from a radio button so it doesn't look like it's not selecting properly?

Ticket: 426837

**Comment by jameskoster** [comment]
Ah, those labels simply shouldn't have the icon.

**Comment by BurlesonBrad** [comment]
I'll do some digging in the BrainTree plugin, but I'm not sure this "issue" is quite closed **_enough_** 


![braintree-checkout-radio-buttons](https://cloud.githubusercontent.com/assets/6208757/15982890/002add1c-2f5b-11e6-9e38-a358d8e76aad.png)

**Comment by jameskoster** [comment]
definitely compiled the css @BurlesonBrad ?
