### ISSUE TITLE
Empty primary menu == strange mobile behavior

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/storefront#408]
If you set an empty menu for the primary location: http://cld.wthms.co/JArc/14yEHH6C (so you're using secondary only), then the mobile menu doesn't work: http://cld.wthms.co/YyOZ/61oisczf

But if you add one item to the primary menu, the mobile menu will correctly display the menu set as "handheld".

**Comment by jameskoster** [comment]
The secondary doesn't display on handheld. That's not it's purpose.

Assigning an empty menu seems like a bizarre thing to do? Not sure we need to support that :p

Ultimately I believe that if you're using the secondary menu as your primary menu, that falls in to the realms of customisation.

**Comment by WPprodigy** [comment]
> The secondary doesn't display on handheld. That's not it's purpose.

Right, but what if it is set to be the "handheld" menu? Then it definiltey should show up as the mobile menu. And it does this correctly if there is something set on the primary menu.

> Assigning an empty menu seems like a bizarre thing to do?

It's necessary if you don't want any links showing up in the primary menu spot. Otherwise, it fills up with all the pages by default.

**Comment by jameskoster** [comment]
OK, I have no idea why that is happening xD

**Comment by jameskoster** [comment]
Just css things. Give that a try please @WPprodigy ?

**Comment by WPprodigy** [comment]
That seems to fix it 👍

**Comment by mikeyarce** [comment]
I've got 2.0.5 running and see a similar issue:
1. Set both Primary and Handheld menus, everything works fine.
2. Remove the Primary Menu.
3. Result:  All pages get added to both Primary and Handheld menus, and some are duplicated in the Handheld menu.

Menu settings:
![screen shot 2016-07-10 at 7 31 59 pm](https://cloud.githubusercontent.com/assets/3220162/16718486/567a43ec-46d5-11e6-88f0-1271ed0f52ee.png)

Handheld Menu: 
![screen shot 2016-07-10 at 7 33 55 pm](https://cloud.githubusercontent.com/assets/3220162/16718490/6083a270-46d5-11e6-8884-4caf890e8cf2.png)

They don't seem to be duplicated in the primary menu:
![screen shot 2016-07-10 at 7 35 23 pm](https://cloud.githubusercontent.com/assets/3220162/16718503/8217d622-46d5-11e6-9992-01628fae8044.png)
