### ISSUE TITLE
WooCommerce 2.6 style tweaks

### ISSUE THREAD

**Issue by bekarice** [woothemes/storefront#411]
@jameskoster I would submit a PR here, but not sure how you'd like this organized (ie should plugin compat CSS go in woocommerce sass, base, or somewhere else if there's no plugin-specific file?). Happy to submit one or just have you include these as you see fit.

I have a few CSS tweaks I've added after WC 2.6 testing, not sure if you'd want some or all added:

```
/* Make the "active" section icon stand out */
.woocommerce-MyAccount-navigation ul li.is-active a:before {
	opacity: 1;
}

/* Icon for Subs tab - WC 2.6+ */
.woocommerce-MyAccount-navigation ul li.woocommerce-MyAccount-navigation-link--subscriptions a:before {
	content: "\f021";
}

/* Icon for PRPro tab - WC 2.6+ */
.woocommerce-MyAccount-navigation ul li.woocommerce-MyAccount-navigation-link--contributions a:before {
	content: "\f005";
}

/* Fix for SV payment gateways "Save card" checkbox */
#payment .payment_methods li input.js-sv-wc-tokenize-payment + label:before {
	display: none;
}

/* Fix for Checkout Add-ons display; wild <br>s appear */
#wc_checkout_add_ons br {
	display: none;
}
```

**Comment by jameskoster** [comment]
Hey Beka!

Hmm, that active account one should already be included, you definitely have the latest version?

For small tweaks, if there's not already a specific stylesheet and the extension doesn't require additional styling we can just roll those into woocommerce.scss.

I'm a little tied up this week, so a PR would be appreciated. If not, I'll just get to it over the weekend xD

**Comment by bekarice** [comment]
> Hmm, that active account one should already be included, you definitely have the latest version?

Perhaps not, I'll update and double-check :) 

> I'm a little tied up this week, so a PR would be appreciated. 

Sure thing, can do later today or tomorrow 👍
