### ISSUE TITLE
Horizontal overflow issue

### ISSUE THREAD

**Issue by opportus** [woothemes/storefront#415]
Since v2.0.1, I get a huge horizontal overflow on the whole page.

Can be reproduced with (at least) a Chromebook touch pad when scrolling any page in some ways...
I use Chrome v51 and didn't try on any other machine or web browser.

The bug has been introduced with the commit 302daa1907d303bc1e5bb387ff25b6f98946eb91 following the issue #389 

The bug disappear when I change back to the previous version of the file `assets/sass/base/_base.scss` with:

    body {
        background-color: $body-background;
        overflow-x: hidden;		
    }
    clearfix {
        @include clearfix;
    }

instead of:

    body {
        background-color: $body-background;
    }
    .site {
        overflow-x: hidden;
    }

**Comment by BurlesonBrad** [comment]
@opportus What Storefront Plugins are you using?

**Comment by opportus** [comment]
None. I can reproduce the bug with just WooCommerce and Storefront installed.

**Comment by jameskoster** [comment]
Interesting. We can add the `overflow-x` back to the `body` tag. We moved it to `.site` because Safari didn't acknowledge it on `body`.

**Comment by opportus** [comment]
Hi @jameskoster 
Sorry but, only now, after the last storefront update, I realize that leaving:

    .site {
        overflow-x: hidden;
    }

doesn't fix the issue.
When I remove the above CSS rule, the overflow won't reappear and it works perfectly.

I don't understand what is going on with it...

**Comment by jameskoster** [comment]
Hmm this needs more investigation before I make any other changes. If I remove that then the horizontal scroll bar appears on Safari. If you have any more information please share.

**Comment by opportus** [comment]
@jameskoster ...
I actually don't have anything around me on which I could test Safari compatibility...
But about the #389 Safari issue, adding the CSS rule to a `<body>` element class wouldn't make the trick ?

**Comment by jameskoster** [comment]
Nope, using a class selector doesn't work :(

**Comment by opportus** [comment]
It seems the Safari issue #389 is in fact a known Safari bug as we can see for example here:
https://bugs.webkit.org/show_bug.cgi?id=153852

I think I've found here different approches to solve the Safari issue without breaking Chrome 51 behavior:
http://stackoverflow.com/questions/3047337/does-overflowhidden-applied-to-body-work-on-iphone-safari

Sadly I can't test them or I'd post a PR already.
As extra info, I tried to reproduce the issue #389 on a IPhone 4s and an old IPad but everything seems to work properly. It was probably old Safari versions which are not concerned by this bug.

**Comment by jameskoster** [comment]
ok, we may have a breakthrough. 

@opportus removing this;

`.site {
	overflow-x: hidden;
}`

Then adding this;

`html,
body {
	overflow-x: hidden;
}`

works fine in Safari. If you can confirm that works for you I'll commit.

**Comment by opportus** [comment]
This and many other things I tried with CSS don't work for me :(

![screenshot](https://cloud.githubusercontent.com/assets/11618989/16268073/17727c2e-388d-11e6-8e72-35e6bb88df33.png)

It seems CSS can't give a solution for both issues.

However I found this answer on stack, which might be interesting for us but I'm not sure that's the best approche:
http://stackoverflow.com/questions/14270084/overflow-xhidden-doesnt-prevent-content-from-overflowing-in-mobile-browsers#answer-14271049

Or what would you think about fixing one or the other or both issue with jQuery ?

**Comment by jameskoster** [comment]
Sorry, I don't fancy using javascript to solve this.

**Comment by acal** [comment]
@jameskoster solution worked for me. Problem occurred today, Nov 2018.
