### ISSUE TITLE
Bug: #payment Styles

### ISSUE THREAD

**Issue by jaswsinc** [woothemes/storefront#419]
A fork of https://github.com/woothemes/storefront/issues/414 (some issues remain).

#### Tested in WooCommerce v2.6.1 + Storefront v2.0.4 + Stripe Ext. v3.0.2

- Attempting to submit the checkout form with invalid or missing details produces an error message, but the `li` tag (in the `.woocommerce-error`) gets a background color that makes it impossible to see the error message. This impacts the checkout `#payment` div, and the same `#payment` div when adding a new payment method from the My Account page also.

- When adding a new payment method from the My Account page, the `::before` icon does not have a font family associated with it, so the icon is broken.

#### Screenshots to help illustrate...

![2016-06-19_21-24-24](https://cloud.githubusercontent.com/assets/1563559/16183980/da36cd1c-3664-11e6-9575-bad06a0d791a.png)

---

![2016-06-19_21-26-12](https://cloud.githubusercontent.com/assets/1563559/16184022/3ebed07c-3665-11e6-88f6-66f0f74165b1.png)

---

![2016-06-19_21-33-09](https://cloud.githubusercontent.com/assets/1563559/16184057/7ebccb20-3665-11e6-9190-e821a47be704.png)

**Comment by jameskoster** [comment]
Ah, ok. It's the saved payment methods that need styling. Will fix that just now. Not seeing the error notice bug you are though. Did you definitely compile the latest scss?

**Comment by jaswsinc** [comment]
Thanks :-)

> Did you definitely compile the latest scss?

I didn't compile it myself for these tests no. I just used the already-compiled Storefront CSS that comes with the theme distro at WordPress.org.

Here's a screenshot of the CSS rule that seems to be causing the problem. If you can't reproduce this just let me know and I'll run through and compile the SCSS from the master branch and try again.

It looks to me like this is coming from the dynamic inline CSS that's generated when using the  WordPress Appearance Customizer. The rule being generated is not quite specific enough?

```css
#payment .payment_methods li {
    background-color: #fafafa;
}
```

![2016-06-20_19-42-41](https://cloud.githubusercontent.com/assets/1563559/16217353/326f544e-371f-11e6-846f-bea191f58d6f.png)

---

![2016-06-20_19-39-01](https://cloud.githubusercontent.com/assets/1563559/16217326/d8179b5a-371e-11e6-91f5-11990953f6fb.png)

**Comment by gedex** [comment]
I experienced the same issue. I can confirm https://github.com/woothemes/storefront/commit/233014aff20c979c4148fd4ce58258d98f502d21 fixes the issue. Thanks @jameskoster !

**Comment by jameskoster** [comment]
thank _you_ @gedex !
