### ISSUE TITLE
Header search broken on Cart page

### ISSUE THREAD

**Issue by RiaanKnoetze** [woothemes/storefront#422]
Link to ticket: 438255-zd-woothemes

When doing a search for a product in the header search widget, while on the Cart page, hitting enter does nothing (hitting enter is required as there's no "submit" button). On ever other page, including checkout, the search section works as expected.

Screenshot at: http://cld.wthms.co/xubb/5Vl4jp9L

Steps to reproduce:

1. Install / activate storefront
2. Add product to cart
3. Go to cart page
4. In search input field in header, type a product name and hit enter (nothing happens - Using Chrome / Mac)
5. Compare that behaviour by doing a search on another page, e.g. home page.

I have replicated this on local and on customer site at https://www.sukkotdevelopment.us (Search for "Sukkah").

**Comment by jameskoster** [comment]
Seems to be a WooCommerce core issue. Will fix there.

**Comment by jameskoster** [comment]
Fixed in https://github.com/woothemes/woocommerce/commit/d0865bdcc78e7d98d3b74855b9edb12c97ecad14
