### ISSUE TITLE
Incompatible with PHP < 5.3 

### ISSUE THREAD

**Issue by WillBrubaker** [woothemes/storefront#424]
Using a closure here: https://github.com/woothemes/storefront/blob/master/inc/customizer/class-storefront-customizer.php#L73-L74

Which, so far as I can tell is causing:

>Parse error: syntax error, unexpected T_FUNCTION in wp-content/themes/storefront/inc/customizer/class-storefront-customizer.php on line 74

in ticket: #440107-zd-woothemes

@jameskoster

**Comment by jameskoster** [comment]
It's the use of the `use` keyword. Whilst not 100% necessary, the code becomes bloated and ugly without it so I think it's worth.

WordPress itself recommends PHP 5.6 and above so I don't think it's a big deal to say Storefront requires 5.3.
