### ISSUE TITLE
storefront_sanitize_hex_color Notice

### ISSUE THREAD

**Issue by dcolumbus** [woothemes/storefront#425]
`Notice: storefront_sanitize_hex_color is deprecated since version 2.0! Use sanitize_hex_color instead. in /var/www/vhosts/mydomain.com/wp-includes/functions.php on line 3658`

Please fix this issue ASAP, as this is plaguing a lot of us who are using Storefront as our parent theme.

**Comment by jameskoster** [comment]
> Please fix this issue ASAP

This isn't an issue for us to fix, it's one for you to fix. 

You (or a plugin) are/is using a deprecated function. That notice even tells you how to fix the problem :)

Just find any instance of `storefront_sanitize_hex_color` in your code and replace it with `sanitize_hex_color`.  If you're using any of our extensions / child themes please update them.

**Comment by dcolumbus** [comment]
The only plugin that I have installed that would use "**storefront**_sanitize_hex_color" would be a WooThemes related Extension or plugin. All are up to date.

Please advise.

**Comment by jameskoster** [comment]
Could you tell me exactly which extensions you have active? I've just checked all of our commercial extensions and none of them reference that function any more. It's possible one of the free ones does though so please let me know.

> And the error doesn't actually tell anyone how to fix it

It does :p

> storefront_sanitize_hex_color is deprecated since version 2.0! Use sanitize_hex_color instead

**Comment by BurlesonBrad** [comment]
since this is duplicated https://wordpress.org/support/topic/notice-on-website-after-update?replies=5#post-8614829 and definitely not a **bug**, can this be locked & limited?

_kinda sux coming here to find a bug to fix, only to find "open support threads"_ :stuck_out_tongue_winking_eye:
