### ISSUE TITLE
page scrolling to the left

### ISSUE THREAD

**Issue by brody182** [woothemes/storefront#426]
add style to stop the website from scrolling to the left because breadcrumbs and main menu are set to -99em

html, body {
  overflow-x: hidden;
}

**Comment by brody182** [comment]
if you are using bourbon I am sure there is a way  to make the main menu and breadcrumbs width 100% without making it -99em because currently it goes off the page

**Comment by jameskoster** [comment]
Are you using the latest version of the theme? I'm not seeing this issue. Which browser are you in? I just tried Chrome, FF and Safari.

> if you are using bourbon I am sure there is a way to make the main menu and breadcrumbs width 

I don't really see how. CSS has no way of figuring out the browser dimensions?

**Comment by brody182** [comment]
you have this that is causing the problem,  and I am using safari  on Storefront Version: 2.0.5

```
.woocommerce-breadcrumb {
padding: 1.387em 99em;
margin-left: -99em;
margin-right: -99em;
margin-bottom: 4.236em }

.storefront-primary-navigation {
clear: both;
background: rgba(0, 0, 0, .06);
margin-left: -99em;
margin-right: -99em;
padding-left: 99em;
padding-right: 99em
}
```

**Comment by brody182** [comment]
place the menu and the breadcrumbs outside of class="col-full", that should fix the issue and only add the class="col-full" inside the menu not the background

**Comment by jameskoster** [comment]
Which version of Safari are you using? I don't want to change something like that without confirming it's actually an issue. As it stands I am unable to replicate.

**Comment by brody182** [comment]
safari 9.1.1,  if you scroll to the left you'll see the site move off the screen
I know you added this: 
```
 body, .site {
    overflow-x: hidden;
}
```

but it should be:
```
 html, body {
overflow-x: hidden;
}
```

**Comment by jameskoster** [comment]
@brody182 Are you sure that's not just the browsers 'back' animation? :p 

Are you running any extensions?

**Comment by jameskoster** [comment]
Assuming you're no longer using the theme and I'm unable to replicate. 

Going to close.

**Comment by brody182** [comment]
try a little harder if you know what you're doing
