### ISSUE TITLE
Product search extension

### ISSUE THREAD

**Issue by ProficientAU** [woothemes/storefront#427]
Hi i am running store front > home store child theme and have purchased the product search extension. 
Could i please get some instructions on how to replace the default search in the top menu with the advanced search I purchased?

**Comment by jameskoster** [comment]
Hey, github isn't the place for support. I recommend posting on the WordPress forums.

Here's a topic where someone did something similar, using Storefront core; https://wordpress.org/support/topic/adding-product-search-extension-to-storefront-header?replies=6

Cheers
