### ISSUE TITLE
Semantic HTML Issues 

### ISSUE THREAD

**Issue by opportus** [woothemes/storefront#437]
Hi @jameskoster 

Storefront is great and diserve a perfect [Nu HTML check](http://validator.w3.org/check?verbose=1&uri=http://sauceweb.net/index.php/2016/06/22/fantastic/).
I could PR a fix for multiple warnings and errors if you'd like...

But here are the **most** problematic issues:

### Structural Elements
There are **multiple** HTML5 structural elements such as `<nav>` and `<section>` missing headings. [**This hurts the pages semantics**](http://html5doctor.com/avoiding-common-html5-mistakes/). As resume very well HTML5 Doctor, the structural elements are **not** wrappers...

### Document Outline
It's messed up on too many pages... from `<h1>` it jumps to `<h3>` without passing by `<h2>`...
On single post, I have a "Navigation de l'article" (post navigation) as `<h2>` !! I believe you did that for screen reader ? But for SEO it's **very bad**.
Suppose you have a keyword which you want to wrap into a `<h2>`, which should be the **only** purpose of `<h*>` tags, the annoying "post navigation" will disolve your keyword impact, and this on **every** single post pages...
Same story about **all widget titles** which should be wrapped into a `<span>` or a `<div>`, at least from a SEO point of view, which is the most important for **any** Storefront site owner. If this is not possible, then I'd strongly recommend using `<h4>` instead of `<h3>` for all of them.

...can we do something about all that ?

**Comment by jameskoster** [comment]
@opportus Yup, there's definitely a lot of stuff we can improve here. A PR would be very much appreciated.

**Comment by opportus** [comment]
@jameskoster 

I'm preparing my first commit right now, but I need to know what do you think about `<div>` instead of `<h3>` for widget titles ?
Let me list the pros and cons about this switch:

**Pros**
- You'll can now say **Storefront is SEO optimized** because it helps search engines to focus on the real content. For me, as a Storefront user, making some money from my e-commerces powered by your theme, this benefit worth **infinitly**  the drawbacks listed below.

**Cons**
- I don't know much about screen readers but I guess it won't help them ? Though, from the few lines I've readed about them, they have other ways to navigate to the widgets than by headings.
- We have to rewrite the CSS concerning widget titles. And between the customizer and the new scss, it's not very clear to me yet how to proceed.

**Comment by lkraav** [comment]
> I'm preparing my first commit right now, but I need to know what do you think about <div> instead of <h3> for widget titles ?

That makes no sense. `h3` tag is used for widget titles all over WP. Are you proposing to do `<div>Some Title</div>` or...? For this proposal, what is the background for the SEO optimization argument again?

**Comment by opportus** [comment]
@lkraav 

It's not because WordPress do it this way, that it's good for SEO. I invite you to analyse other websites than the ones powered by WordPress. Website makers aware of good practices in SEO optimization would avoid putting headings everywhere. Especially if it's not content related.

**Comment by lkraav** [comment]
How is a widget title not content related again?

**Comment by opportus** [comment]
Simply put... does "Search" or "New Comment" or "Category" etc... would have any direct relation with the main content relating about, say, "Mister lkraav is not liking people caring about his site position in Google"... No.
In this situation, even the tag `<aside>` should not wrap the widget, which WordPress do right ?
http://www.anthonycalzadilla.com/2010/08/html5-section-aside-header-nav-footer-elements-not-as-obvious-as-they-sound/

**Comment by lkraav** [comment]
> Simply put... does "Search" or "New Comment" or "Category" etc... would have any direct relation with the main content relating about, say, "Mister lkraav is not liking people caring about his site position in Google"... No.

Somewhat matter of interpretation and quite a lot up to the individual site to determine. But see below.

> In this situation, even the tag <aside> should not wrap the widget, which WordPress do right?

Whatever case, this doesn't look like it's Storefront's job to be the odd man out and try to solve the problem alone (if it actually is a problem in the first place). Have you filed a ticket on WP issue tracker https://core.trac.wordpress.org yet? Certainly having a supposedly very non-optimized base to work from should be the core WP team's job to fix? I'd be super interested in reading some core ticket discussion on this topic.

**Comment by opportus** [comment]
@lkraav 

> Have you filed a ticket on WP issue tracker https://core.trac.wordpress.org yet?

Frankly, I'm busy enough contributing to WooCommerce and Storefront which is the first level of interaction between my customers and my sites. You still can bring my voice in https://core.trac.wordpress.org if you'd like contributing to it.

> Certainly having a supposedly very non-optimized base to work from should be the core WP team's job to fix?

Don't forget the sense of the word "optimization" that I used in my comments. Having actually a such base is not "catastophic" but can still be improved from a SEO point of view.

**Comment by opportus** [comment]
@lkraav  and for those not being aware of the advantages of using `<div>` instead of `<h3>` for widget titles. Forgive me if I was not clear enough in my first message. I try to resume here.

Spiders scan your site, trying to understand its content hugely from your **headings**.
Now, what do you want your content to be in the eyes of Google ? Your widgets title or your **real content** titles ? What we need to know here is that a nonsense heading such as "Category" will simply **disolve**, more or less, the impact of your meaningful headings in which you put your keywords.
Now add 10 widgets having a `<h3>` element wrapping a randon string on every pages of your site...

I'm aware that headings in `<aside>` might have less weight than headings in main content, hopefully, but still has because of the same reason that they are in `<aside>`, which is a tag for **directly related content**, that should be used in a perfect world as wrapper for say, posts meta.
> aside – Used for tangentially related content. Just because some content appears to the left or right of the main content isn’t enough reason to use the aside element. Ask yourself if the content within the aside can be removed without reducing the meaning of the main content. Pullquotes are an example of tangentially related content.

> It is easy to confuse this element for something it isn’t, and as mentioned earlier the definition of `<aside>` can trip-up a few developers. The most common misconception of how this element should be used is for the standard sidebar. While there is usually a degree of relation between sidebar content and the content in an article, it is not enough to be considered fit for an <aside>. Navigation, ads, search boxes, blogrolls and so on are not directly related to the article and therefore do not justify the use of an `<aside>`.

Please, [educate](http://html5doctor.com/understanding-aside/) yourself before to accuse me of trying to create a conspiracy.

**Comment by jameskoster** [comment]
@opportus sorry for the delay getting back to you.

Re: widget titles, this is tricky. I totally see and understand the pros, especially for an eCommerce web site where the widgets rarely contain content that is valuable from an SEO perspective. But the lack of hierarchy feels wrong to me.

I am not an SEO expert. Would using `h5`s have a significant negative impact on the main content titles? I think that would be my preference tbh. Seeing as everyone else is using `h3`s that would at least improve your ranking vs others right? xD

FWIW Shopify also uses `h3`s and Magento uses `h2`s  😮

Don't worry about the styling, I'm happy to take care of that.

**Comment by opportus** [comment]
Hi @jameskoster 

I'm not SEO "expert" too. I just share what I've learn on the web and from direct advices I got from SEO experts concerning my websites powered by WordPress.

The main point here is not to improve Storefront for myself, I already have my child themes set the way I want :) I just want contributing to it...
If you think that `<h5>` would be good then I think the same. It seems a very good compromise.

Glad to hear that you'll take care of the CSS :)

**Comment by opportus** [comment]
@jameskoster 
You can see BTW on YOAST website that they don't use `aside` in sidebar or footer.
They also dont use `<h*>` tags for widget titles but `<span>`...

**Comment by opportus** [comment]
It would be nice if @jdevalk can enlight us a little bit from his expertise :)

**Comment by jameskoster** [comment]
I'm totally happy with not using `aside`.

For the headings, let's go with a `div` and make the args filterable so folks can easily change if they want.
