### ISSUE TITLE
Comments background color

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/storefront#440]
Seems like comments now use a different background color from the customization options:

![](http://cld.wthms.co/1d2Oi/3Fz42iIu+)

I think they should be the same bg color of the main container.

That above is a post author's comment, but it's the same for users.

**Comment by jameskoster** [comment]
Hmm, I wonder if you have a left over setting from a previous Storefront version. Definitely not seeing that here. Would you mind resaving Customizer settings, or performing a [Customizer Reset](https://wordpress.org/plugins/customizer-reset-by-wpzoom/) to see if that resolves?

**Comment by SiR-DanieL** [comment]
If I look at the page with the Customizer open I see this color

![](http://cld.wthms.co/f2PJ/ofreCcsl+)

But if I save and/or look at it with the Customizer closed it appears darker.
Might it be a Storefront Designer issue? I have the same problems on 2 websites where I'm using it.

**Comment by jameskoster** [comment]
Just tried with Designer active, I'm still unable to replicate :s Did you definitely save changes in the Customizer? And try a reset? Do you have some other plugins active?

**Comment by SiR-DanieL** [comment]
Not an issue. Discussed in Slack.
