### ISSUE TITLE
Duplicate Search Form ID

### ISSUE THREAD

**Issue by opportus** [woothemes/storefront#446]
The product search forms in header and mobile footer have the same ID.

![duplicate-search-form-id](https://cloud.githubusercontent.com/assets/11618989/17221073/717d4754-54f2-11e6-9758-fc56371ae66c.png)

**Comment by jameskoster** [comment]
Probably better to fix this in WooCommerce.  The search forms in Storefront are instances of the product search widget which calls a WooCommerce template. It's conceivable that sites will include multiple instances of that widget so we shouldn't use an ID on that input.
