### ISSUE TITLE
Missing breadcrumb on product search page

### ISSUE THREAD

**Issue by opportus** [woothemes/storefront#447]
![missing-margin](https://cloud.githubusercontent.com/assets/11618989/17221297/9936cabc-54f3-11e6-8115-bd1183ecc577.png)

**Comment by jameskoster** [comment]
> Or should the title be "Missing breadcrumb on product search page" ?

That

**Comment by jameskoster** [comment]
@opportus Hmm, I just tried to replicate this and was unable to; https://cloudup.com/c3O1jZc4OQl

You have any plugins active that might interfere with the search template?

**Comment by opportus** [comment]
@jameskoster  Strange... nop, on my test site I don't have anything else than WooCommerce and Storefront. And I can confirm that it does the same on my stores.

**Comment by jameskoster** [comment]
Hmm, doesn't happen on any of my sites or our demos. 

@tiagonoronha could you see if you can replicate please?

**Comment by opportus** [comment]
@jameskoster 
After some debugging, it becomes clear enough that the bug comes from `woocommerce_breadcrumb()` or the breadcrumb class itself... I will check it deeper when I'll have time. You can close this after we get info from @tiagonoronha if you want.
