### ISSUE TITLE
Product images disappear when using the customizer

### ISSUE THREAD

**Issue by ryanr14** [woothemes/storefront#448]
Just came across this when creating a video for WooCommerce widgets. As soon as I open the customizer and view the shop page, my product images are no longer there. I assume that isn't on purpose? :)

Normal View
![screen shot 2016-07-30 at 3 43 57 pm](https://cloud.githubusercontent.com/assets/867748/17272739/751e51c0-566c-11e6-8b08-548188810fea.png)

Customizer View
![screen shot 2016-07-30 at 3 44 22 pm](https://cloud.githubusercontent.com/assets/867748/17272743/8554503a-566c-11e6-8397-9ff4de1338ad.png)

**Comment by jameskoster** [comment]
That's very strange. Not happening here 💭 

Running the latest versions of everything? Got any plugins active?

**Comment by BurlesonBrad** [comment]
Stop breaking the innerwebs @ryanr14 !
![storefront-product-images-in-customizer](https://cloud.githubusercontent.com/assets/6208757/17297459/6893dfa0-57cb-11e6-9571-3305e0f5d6f0.png)

If you need support for Storefront, please open a thread in the Theme forums located here:
https://wordpress.org/support/theme/storefront
One of the WooCommerce Ninjas will be able to help you out.  

Github is for bugs only.  

And, any member of the innerwebs caught asking for **support** in Github is subjected to @claudiosmweb setting you straight.  

Now, any member/employee of WooCommerce/Automattic caught breaking that rule, and asking for **support** in Github is further subjected to @claudiosmweb cussing you out in some foreign language that is so damn funny to read for everyone else, that we all read it, crack up laughing, and roll on the floor wiping tears from our eyes, and possibly pee a little from uncontrollable laughter, at the humor and irony of the whole situation.

**Comment by ryanr14** [comment]
Sorry @jameskoster! I realized (forgot) I'm on the Release Candidate 1 for WordPress 4.6 making videos with the new system font ahead of time. I put the site back on WordPress 4.5.3 and all is well in the customizer regarding product images. DOH.

<img width="964" alt="screen shot 2016-08-01 at 4 21 29 pm" src="https://cloud.githubusercontent.com/assets/867748/17307634/1839d0f8-5804-11e6-83ed-5adff568036d.png">

Now I put the site back on 4.6 and the images work... SO problem solved!?#

<img width="951" alt="screen shot 2016-08-01 at 4 24 28 pm" src="https://cloud.githubusercontent.com/assets/867748/17307706/77e1ced4-5804-11e6-8669-05362b610693.png">

**Comment by jameskoster** [comment]
Whew!
