### ISSUE TITLE
Cannot `remove_action/filter` for hooks in `Storefront`

### ISSUE THREAD

**Issue by jtsternberg** [woothemes/storefront#457]
Since the Storefront object [is initiated without casting to a variable](https://github.com/woothemes/storefront/blob/master/inc/class-storefront.php#L401), or using a singleton, there is no way for me to unhook the `child_scripts` method (for example) from my child theme without re-creating the Storefront class myself (causing the `class_exists` check to return true). These hooks (as with most any hook in WordPress), should be accessible for removing.

**Comment by jameskoster** [comment]
This is a pretty widespread 'issue', especially in plugins. None of the methods on the storefront class should be removed tbh. If you want to remove the child theme stylesheet you can do so with `wp_dequeue_style()` ?

**Comment by lkraav** [comment]
"Should not be" is a large assumption surface. One of the baseline reasons for allowing sane manipulation of actions/filters is so that people could sanely experiment on things. I support @jtsternberg here.

**Comment by jameskoster** [comment]
PR's are always welcome ;)

I generally agree in principle, but I think if you look at the class you'd agree that there really isn't anything you'd want to flat-out _remove_. There are things you might want to tweak, and there are filters that allow you to do just that.

**Comment by jtsternberg** [comment]
Agree with @Ikraav, you're making assumptions based on your perspective of how storefront will be/should be used. Ultimately, if you want to limit how others use your theme, that's your prerogative. Personally, I'm not fond of the idea of limiting how others can and should use my code. I'll issue a PR if there is a decent chance of review and merging. Otherwise, an issue is a better way to gauge that interest, and seems like it was a good idea in this case to do just that as it does not sound like you're interested in the proposed changes.

**Comment by lkraav** [comment]
@jtsternberg definitely file a PR, @jameskoster has been a fine steward to the project.

**Comment by jameskoster** [comment]
> as it does not sound like you're interested in the proposed changes

We're interested, it's just not a priority because as I said I don't personally believe it's necessary. But you're right, there's no way I can know that for sure.

A PR would be most welcome.

**Comment by jtsternberg** [comment]
Ok, PR submitted. Thanks! #459
