### ISSUE TITLE
Z-Index on Storefront 2.1Menu

### ISSUE THREAD

**Issue by BurlesonBrad** [woothemes/storefront#460]
![z-index-on-menu](https://cloud.githubusercontent.com/assets/6208757/17943161/ddce3856-69ff-11e6-8b9b-f2c4f5b1d103.png)

![z-index1](https://cloud.githubusercontent.com/assets/6208757/17943413/e8396c1a-6a00-11e6-879e-6a9ce1750958.png)

![z-index2](https://cloud.githubusercontent.com/assets/6208757/17943414/e83c697e-6a00-11e6-8522-75527ce49f53.png)

**Comment by opportus** [comment]
Hi Brad, as a complement, I'll add that it maybe comes from Storefront Designer incompatibility with the new styles.
@jameskoster, to reproduce, use the extension plugin. There's only one header layout producing this issue.

Spent too much time trying to find a fix to this last time... And it appears that it's not being a problem with the `z-index`.

**Comment by BurlesonBrad** [comment]
sorry. I ran a quick fly by of the new release and didn't really check exactly **_what_** was causing it. Lemme get the girls settled & home from school, then I'll open a ticket so that someone can check the Storefront Designer Extension.

**Comment by tiagonoronha** [comment]
Hi! As @opportus mentioned, the issue is caused by Storefront Designer. 

An update for that extension will be available today.

**Comment by RamyTalal** [comment]
Will this also be fixed?

<img width="576" alt="schermafbeelding 2016-08-25 om 16 44 49" src="https://cloud.githubusercontent.com/assets/188874/17973575/45db399c-6ae3-11e6-98ac-14ad32183d08.png">

**Comment by tiagonoronha** [comment]
@RamyTalal yes!

**Comment by BurlesonBrad** [comment]
sorry. i knew I should've delete this one last night :hushed: Now, in the middle of _#AlwaysBeLearning_ I'm getting notifications for this too :sob: @tiagonoronha feel free to lock & limit :+1:
