### ISSUE TITLE
Live changes not showing when using wordpress default customizer, header color changes etc.

### ISSUE THREAD

**Issue by boloshabashe** [woothemes/storefront#462]
its only when you save the customization you are able to see the changes , I wanted to see live color changes in the header so that I may choose the one which is looking better , but now I have to first save the color and then refresh the site and see how it looks :)
I am not even sure is it happening because of the theme or do i have any other issues :)
 I updated storefront to 2.1 yesterday 
Thanks

**Comment by tiagonoronha** [comment]
@boloshabashe are you using the latest version of WordPress, 4.6?

**Comment by boloshabashe** [comment]
yes :)

**Comment by boloshabashe** [comment]
I also tried site origin visual css to see live changes happening , the background color is changing live but the header and footer needs a save to see what it looks like :)

**Comment by tiagonoronha** [comment]
Confirmed, thanks for the report!

**Comment by opportus** [comment]
Hi @tiagonoronha 

Changing from the `transport` from `postMessage` to `refresh` in 7df3c93 was the only solution ?
This seems to me like a downgrade...

**Comment by opportus** [comment]
Hi @tiagonoronha 

Changing the `transport` arg from `postMessage` to `refresh` in 7df3c93 was the only solution ?
This seems to me like a downgrade...

**Comment by jameskoster** [comment]
@opportus we decided to move away from relying on js for these previews for a couple of reasons;

* Child themes - There's no clean and simple way for child themes to interact with the js. This results in inaccurate previews in some child themes / extensions.
* Pseudo classes - It's not possible to target pseudo selectors as the styles are added inline.
* Selective refresh is the future. We can't implement it for all of our settings yet but is the direction we want to move in.
* Maintainability - Storefront uses some settings in many places. Frankly it's a pain to maintain all of the selectors.

**Comment by boloshabashe** [comment]
@tiagonoronha  @jameskoster  Thanks :)
