### ISSUE TITLE
Filtering Plugin

### ISSUE THREAD

**Issue by tomhoad** [woothemes/storefront#463]
More a question than an issue - can you recommend a filtering plugin that actually works with Storefront? Basic filtering of tags and subcategories.

**Comment by tiagonoronha** [comment]
We don't have a specific plugin that we recommend. You'll probably need to tweak the styling if the plugin adds their own css.

Perhaps it is better if you ask this question in the public forums: https://wordpress.org/support/theme/storefront

Thanks!
