### ISSUE TITLE
Post Format support

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/storefront#464]
I know that Storefront is more a Shop theme than a blog theme, but it would be cool to add support for post formats and have a specific style for them.

**Comment by jameskoster** [comment]
We originally planned to make a plugin for this. Haven't seen anyone request it yet though so it's low down on the list of priorities for now.

**Comment by jameskoster** [comment]
Gonna close this issue in favour of this [idea](http://ideas.woothemes.com/forums/275029-storefront/suggestions/15969271-release-a-plugin-that-adds-post-format-styling-to).
