### ISSUE TITLE
Sticky order review element is not blocked by overlay on scroll

### ISSUE THREAD

**Issue by jlad26** [woothemes/storefront#468]
Hi there
I think the use of the sticky order_review element means that once payment details have been submitted
the bottom of the order_review element (i.e., including the Continue to payment button) can stick out underneath the blocking overlay that Woocommerce puts over the Checkout form. Screenshot attached.

I did wonder whether it could be easily fixed using css to change the overlay to position: fixed but I think the Woocommerce plugin defines the overlay element with an inline style of position absolute - in this section from assets/js/jquery-blockui/jquery.blockUI.js

```
// style the overlay
if (!opts.theme /*&& (!opts.applyPlatformOpacityRules)*/)
    lyr2.css(opts.overlayCSS);
lyr2.css('position', full ? 'fixed' : 'absolute');
```

(full is only true if the element that the block function is being called on is window)

So sorry - haven't got any useful suggestions for a fix.
Jon
![example](https://cloud.githubusercontent.com/assets/8443297/18310150/ca618b56-74f4-11e6-8f36-a7391371a543.png)

**Comment by jameskoster** [comment]
Hmm, yeah this is tricky as the overlay is displayed over the checkout div which the overview 'sticks out' of. The only work around I can think for that would be to make the overlay cover the entire page. I'll give that a try and see how it looks.
