### ISSUE TITLE
Enhancement: Make menu's keyboard accessible

### ISSUE THREAD

**Issue by mikeyarce** [woothemes/storefront#471]
We had a report of Storefront's menu not being keyboard accessible for dropdown's, you can see an example here:
![keyboard-accessible](https://cloud.githubusercontent.com/assets/3220162/18361619/726260c4-75b7-11e6-86d8-cc8e5592f50d.gif)
When you navigate through the menu, when the parent item looses `focus`, the sub-menu disappears.

I looked into some solutions to make this accessible and we have 2 options:
1. We can use the off-left css hack, which is pretty wild but would be a good CSS only solution:
http://thinkhtml.blogspot.in/2009/09/timos-float-drop-css-only-dropdown-menu.html
2. We can add some JS similar to `superfish.js`
https://github.com/joeldbirch/superfish

@jameskoster any thoughts on what approach we should take?  I'd be happy to work on this improvement once we figure out a direction.

**Comment by jameskoster** [comment]
That's odd. Tabbing through the menu should include the dropdown. It definitely used to. Will have to hunt down what caused that to break.
