### ISSUE TITLE
Advanced Products Labels

### ISSUE THREAD

**Issue by el-presidente** [woothemes/storefront#474]
I don't find that the new 'integration' in 2.1.0 with Advanced Products Labels works or maybe I just can't find out what is needed.

I just get a empty global red label underneath even though I've turned global labels off:

![screen shot 2016-09-13 at 13 12 56](https://cloud.githubusercontent.com/assets/937382/18471797/d5a6b2a2-79b3-11e6-9f68-29b4b70b7dd8.png)

I had hoped some integration would be the possibility to set labels that looks like the CSS class="onsale" today as I like the style.

Would that be possible in some other way on specific products? Could I add the CSS for that specific product and a label?

**Comment by jameskoster** [comment]
Hey, sorry about this, it's an oversight that will be fixed in the next release. Here's the code if you want to grab it right now;

https://github.com/woothemes/storefront/commit/838e7b6f4831503ae1d83a3650703bab6575ed89

**Comment by el-presidente** [comment]
Thanks - my second question or wish, maybe I should direct it at the Advanced Product Labels plugin, but I would like to be able to make custom labels like the Sale! label, fx New! or Reduced! - as it is today I cannot get the same style/layout on the label, so is there some CSS or hook that I could use on specific products?

![screen shot 2016-09-18 at 16 34 01](https://cloud.githubusercontent.com/assets/937382/18616534/f68dfeea-7dbd-11e6-8e9c-9133028633bb.png)
![screen shot 2016-09-18 at 16 34 09](https://cloud.githubusercontent.com/assets/937382/18616535/f68edcf2-7dbd-11e6-925e-38a669c361d1.png)

**Comment by opportus** [comment]
Hi @el-presidente 

Your question may be WooCommerce related and not really an issue but if I understand right what you need...

Loop product label hook:
https://github.com/woothemes/woocommerce/blob/master/templates/content-product.php
```php
/**
  * woocommerce_before_shop_loop_item_title hook.
  *
  * @hooked woocommerce_show_product_loop_sale_flash - 10
  * @hooked woocommerce_template_loop_product_thumbnail - 10
  */
do_action( 'woocommerce_before_shop_loop_item_title' );
```

Single product label hook:
https://github.com/woothemes/woocommerce/blob/master/templates/single-product/sale-flash.php
```php
apply_filters( 'woocommerce_sale_flash', '<span class="onsale">' . __( 'Sale!', 'woocommerce' ) . '</span>', $post, $product );
```

CSS class:
`.onsale`
