### ISSUE TITLE
Should 'brand' on storefront-woocommerce-template-functions.php be translatable?

### ISSUE THREAD

**Issue by webdados** [woothemes/storefront#475]
I'm completing the Portuguese (Portugal) translation of Storefront on WooCommerce.org and I'm wondering if the string 'brand' found at line 353 of storefront-woocommerce-template-functions.php should be translatable at all.

Isn't this an attribute slug / internal stuff? Is it supposed to change if the website language is not English?

**Comment by opportus** [comment]
Hi @webdados 

This is meant to detect if the admin has set up a 'brand' attribute in his own language.
However this feature should be removed soon from Storefront since WooCommerce will take care of this itself in v2.7.

**Comment by webdados** [comment]
OK, I'll leave it untranslated anyway :-D

**Comment by jameskoster** [comment]
@opportus you wanna create an issue for that? :)

**Comment by opportus** [comment]
Hi @jameskoster 

I will PR the update as soon as I can 👍 
Up to you then when to merge it...

**Comment by jameskoster** [comment]
Sounds good!
