### ISSUE TITLE
responsive table styles for WooCommerce 2.3

### ISSUE THREAD

**Issue by jameskoster** [woothemes/storefront#48]

**Comment by hieu-n** [comment]
Hi, I was searching for a way to create a responsive table in my production description and Google took me here. If anyone would show me how, that would be great.

I tried `<table class="shop_table_responsive >`, but the table isn't responsible.

**Comment by jameskoster** [comment]
If you're using the Storefront theme it should be. You will also need to add a `data-title` attribute to each `td` though.

Have a look at the Cart markup as a guide.
