### ISSUE TITLE
Removing actions from storefront_header

### ISSUE THREAD

**Issue by jameswlane** [woothemes/storefront#94]
I made a child theme using Storefront, and I am trying to remove: 
* storefront_header_widget_region
* storefront_site_branding
* storefront_secondary_navigation

I added in my child themes ```functions.php```
```
    remove_action( 'storefront_header', 'storefront_header_widget_region', 20 );
    remove_action( 'storefront_header', 'storefront_site_branding', 20 );
    remove_action( 'storefront_header', 'storefront_secondary_navigation', 30 );
```

And its not working. What the best way to remove added actions set by storefront in a child theme?

**Comment by jameskoster** [comment]
Hi, please don't post support on github, use the wordpress.org forums.

You need to add a new function into `init` to do this, the reason being that the child themes functions.php is loaded before the parent theme. So with your code you're removing them before they've actually been added in the first place.
