### ISSUE TITLE
"Enhanced" css for Select, Checkboxes, Radio buttons, etc

### ISSUE THREAD

**Issue by jan1980** [woothemes/storefront#96]
Hi guys, thanks for this awesome theme that we are using in our last project.

I was wondering if it's possible to "recover" the styles for the select dropdowns (and other input / form stuff) on the single product view (variations).

We used to have with Woocommerce some great defaults on there, but Storefront seems to get rid of them somehow.

Is there any way to turn them back on?

Many thanks,
Jan

**Comment by jameskoster** [comment]
WooCommerce has never applied styles to checkboxes or `select`s on that page. Perhaps you were using a theme that did before.

The short answer is that we probably wont add this to Storefront core, but you can do so yourself via child theme fairly easily :-)
