### ISSUE TITLE
Issue with some notices

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/storefront#97]
Some notices with Point & Rewards look like this http://cld.wthms.co/1hwdk
It's the Apply points discount notice in the cart

**Comment by jameskoster** [comment]
Hmm, is that border added by P&R?

**Comment by SiR-DanieL** [comment]
No by WooCommerce style in Storefront

**Comment by jameskoster** [comment]
Ah, it happens when you're using transparent buttons in the designer extension. Will fix.
