### ISSUE TITLE
Replace gridset with susy

### ISSUE THREAD

**Issue by jameskoster** [woothemes/storefront#99]
http://susydocs.oddbird.net/en/latest/install/

**Comment by benjaminluoma** [comment]
How would you suggest theme developers employ your grid system?  I'm just experimenting with child themes for storefront and I've been including your gridset in my child theme's sass.  But really I want a future proof way of leveraging all your hard work ;-) vs. adding my own grids or using another framework (unnecessarily).

**Comment by jameskoster** [comment]
Hey @benjaminluoma, that's awesome to hear that you're building on top of our grid.

With the next release however, the gridset.scss file is removed so you're going to get an error when compiling your sass file. 

I'd recommend adopting the Susy approach. I wish I'd known about this before building Storefront as I wouldn't have bothered with Gridset at all.

If you're using Grunt, there's a guide on installing and including Susy in your project here: http://susydocs.oddbird.net/en/latest/install/#grunt-and-yeoman As you'd imagine it's very simple. Then you'll just need to get to grips with the syntax and remember to import our _variables.scss file to ensure your grid matches the Storefront one. Looking through this commit (https://github.com/woothemes/storefront/commit/4b722729a6042eaa039fd7a2fcba71df535fca4a) should be a good starting point on that.

I'm going to be working on a Storefront child theme very soon which will eventually result in our releasing a 'boilerplate' of sorts for this type of project. Keep an eye out for that.

I'll close this issue as it's not reporting a bug, but feel free to continue the convo :-)
